//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMonederoCommand.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppMonederoCommand.Business.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            font-family: Arial, Helvetica, sans-serif;
        ///        }
        ///
        ///        .seccion {
        ///            width: 100%;
        ///        }
        ///
        ///        .centrado {
        ///            text-align: center;
        ///        }
        ///
        ///        .saludo {
        ///            margin-top: 2rem;
        ///            marg [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ActivacionCuenta {
            get {
                return ResourceManager.GetString("ActivacionCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div style=&quot;padding: 0 20px&quot;&gt;
        ///  &lt;span style=&quot;margin-bottom: 0 !important; color: #a9a9a9; font-size: 1em&quot;
        ///    &gt;{0}&lt;/span
        ///  &gt;
        ///  &lt;h2
        ///    style=&quot;font-size: 1.5em; color: #333333; margin-top: 0; margin-bottom: 10px&quot;
        ///  &gt;
        ///    {1}
        ///  &lt;/h2&gt;
        ///  &lt;p style=&quot;font-size: 1em; color: #5e6d76&quot;&gt;
        ///    &lt;span style=&quot;font-weight: bold&quot;&gt;{7}, {Nombre}:&lt;/span&gt;&lt;br /&gt;
        ///    &lt;span&gt;{3}&lt;/span&gt;
        ///  &lt;/p&gt;
        ///  &lt;div style=&quot;border-top: 1px dashed #ededed; margin: 20px 0&quot;&gt;&lt;/div&gt;
        ///  &lt;p style=&quot;font-size: 1em; font-style: italic; color: #a9a9 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Bienvenido {
            get {
                return ResourceManager.GetString("Bienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div style=&quot;padding: 0 20px&quot;&gt;
        ///    &lt;span style=&quot;margin-bottom: 0 !important; color: #a9a9a9; font-size: 1em&quot;&gt;
        ///        {0}
        ///    &lt;/span&gt;
        ///    &lt;h2 style=&quot;font-size: 2.5em; color: #333333; margin-top: 0; margin-bottom: 10px&quot;&gt;
        ///        {1}
        ///    &lt;/h2&gt;
        ///    &lt;p style=&quot;font-size: 1em; color: #5e6d76&quot;&gt;
        ///        &lt;span style=&quot;font-weight: bold&quot;&gt;{2}&lt;/span&gt;&lt;br /&gt;
        ///    &lt;/p&gt;
        ///    &lt;p style=&quot;font-size: 1em; color: #5e6d76&quot;&gt;
        ///        &lt;span&gt;{3}&lt;/span&gt;
        ///    &lt;/p&gt;
        ///
        ///    &lt;div style=&quot;border-top: 1px dashed #ededed; margin: 20px 0 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string CodeEliminaCuenta {
            get {
                return ResourceManager.GetString("CodeEliminaCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div style=&quot;padding: 0 20px&quot;&gt;
        ///  &lt;span style=&quot;margin-bottom: 0 !important; color: #a9a9a9; font-size: 1em&quot;
        ///    &gt;{0}&lt;/span
        ///  &gt;
        ///  &lt;h2
        ///    style=&quot;font-size: 1.5em; color: #333333; margin-top: 0; margin-bottom: 10px&quot;
        ///  &gt;
        ///    {1}
        ///  &lt;/h2&gt;
        ///  &lt;p style=&quot;font-size: 1em; color: #5e6d76&quot;&gt;
        ///    &lt;span style=&quot;font-weight: bold&quot;&gt;{7}, {Nombre}:&lt;/span&gt;&lt;br /&gt;
        ///    &lt;span&gt;{2} {3} {4}&lt;/span&gt;
        ///  &lt;/p&gt;
        ///  &lt;div style=&quot;border-top: 1px dashed #ededed; margin: 20px 0&quot;&gt;&lt;/div&gt;
        ///  &lt;p style=&quot;font-size: 1em; color: #5e6d76&quot;&gt;
        ///    &lt;s [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string EliminaCuenta {
            get {
                return ResourceManager.GetString("EliminaCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;table
        ///  border=&quot;0&quot;
        ///  role=&quot;presentation&quot;
        ///  cellpadding=&quot;0&quot;
        ///  cellspacing=&quot;0&quot;
        ///  width=&quot;100%&quot;
        ///  style=&quot;background-color: #f4f8ff&quot;
        ///&gt;
        ///  &lt;tbody&gt;
        ///    &lt;tr&gt;
        ///      &lt;td align=&quot;center&quot; valign=&quot;top&quot;&gt;
        ///        &lt;table
        ///          align=&quot;center&quot;
        ///          border=&quot;0&quot;
        ///          cellpadding=&quot;0&quot;
        ///          cellspacing=&quot;0&quot;
        ///          width=&quot;600&quot;
        ///        &gt;
        ///          &lt;tbody&gt;
        ///            &lt;tr&gt;
        ///              &lt;td valign=&quot;top&quot; style=&quot;padding: 20px&quot;&gt;
        ///                &lt;div
        ///                  style=&quot;
        ///                    [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div style=&quot;padding: 0 20px&quot;&gt;
        ///  &lt;span style=&quot;margin-bottom: 0 !important; color: #a9a9a9; font-size: 1em&quot;
        ///    &gt;{0}&lt;/span
        ///  &gt;
        ///  &lt;h2
        ///    style=&quot;font-size: 1.5em; color: #333333; margin-top: 0; margin-bottom: 10px&quot;
        ///  &gt;
        ///    {1}
        ///  &lt;/h2&gt;
        ///  &lt;p style=&quot;font-size: 1em; color: #5e6d76&quot;&gt;
        ///    &lt;span style=&quot;font-weight: bold&quot;&gt;{9}, {Nombre}:&lt;/span&gt;&lt;br /&gt;
        ///    &lt;span&gt;{2}&lt;/span&gt;
        ///  &lt;/p&gt;
        ///  &lt;div style=&quot;border-top: 1px dashed #ededed; margin: 20px 0&quot;&gt;&lt;/div&gt;
        ///  &lt;a
        ///    style=&quot;
        ///      text-decoration: none;
        ///      backg [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string RecuperaPass {
            get {
                return ResourceManager.GetString("RecuperaPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div style=&quot;padding: 0 20px&quot;&gt;
        ///  &lt;span style=&quot;margin-bottom: 0 !important; color: #a9a9a9; font-size: 1em&quot;
        ///    &gt;{0}&lt;/span
        ///  &gt;
        ///  &lt;h2
        ///    style=&quot;font-size: 1.5em; color: #333333; margin-top: 0; margin-bottom: 10px&quot;
        ///  &gt;
        ///    {1}
        ///  &lt;/h2&gt;
        ///  &lt;div style=&quot;border-top: 1px dashed #ededed; margin: 20px 0&quot;&gt;&lt;/div&gt;
        ///  &lt;p style=&quot;font-size: 1em; color: #5e6d76&quot;&gt;
        ///    &lt;span&gt;{2}&lt;/span&gt;&lt;br /&gt;
        ///    &lt;span&gt;{Tipo}&lt;/span&gt;
        ///  &lt;/p&gt;
        ///  &lt;p style=&quot;font-size: 1em; color: #5e6d76&quot;&gt;
        ///    &lt;span&gt;{3}&lt;/span&gt;&lt;br /&gt;
        ///    &lt;span&gt;{Fecha}&lt;/s [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Sugerencias {
            get {
                return ResourceManager.GetString("Sugerencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div style=&quot;padding: 0 20px&quot;&gt;
        ///  &lt;span style=&quot;margin-bottom: 0 !important; color: #a9a9a9; font-size: 1em&quot;
        ///    &gt;{0}&lt;/span
        ///  &gt;
        ///  &lt;h2
        ///    style=&quot;font-size: 1.5em; color: #333333; margin-top: 0; margin-bottom: 10px&quot;
        ///  &gt;
        ///    {1}
        ///  &lt;/h2&gt;
        ///  &lt;p style=&quot;font-size: 1em; color: #5e6d76&quot;&gt;
        ///    &lt;span style=&quot;font-weight: bold&quot;&gt;{7}, {Nombre}:&lt;/span&gt;&lt;br /&gt;
        ///    &lt;span&gt;{2}&lt;/span&gt;
        ///  &lt;/p&gt;
        ///  &lt;div style=&quot;border-top: 1px dashed #ededed; margin: 20px 0&quot;&gt;&lt;/div&gt;
        ///  &lt;p
        ///    style=&quot;
        ///      font-size: 2em;
        ///      color: #c922 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string TemporalPass {
            get {
                return ResourceManager.GetString("TemporalPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div style=&quot;padding: 0 20px&quot;&gt;
        ///  &lt;span style=&quot;margin-bottom: 0 !important; color: #a9a9a9; font-size: 1em&quot;
        ///    &gt;{0}&lt;/span
        ///  &gt;
        ///  &lt;h2
        ///    style=&quot;font-size: 1.5em; color: #333333; margin-top: 0; margin-bottom: 10px&quot;
        ///  &gt;
        ///    {1}
        ///  &lt;/h2&gt;
        ///  &lt;p style=&quot;font-size: 1em; color: #5e6d76&quot;&gt;
        ///    &lt;span style=&quot;font-weight: bold&quot;&gt;{4}, {Nombre}:&lt;/span&gt;&lt;br /&gt;
        ///    &lt;span&gt;{Mensaje}&lt;/span&gt;
        ///  &lt;/p&gt;
        ///  &lt;div style=&quot;border-top: 1px dashed #ededed; margin: 20px 0&quot;&gt;&lt;/div&gt;
        ///  &lt;p style=&quot;font-size: 1em; color: #5e6d76&quot;&gt;
        ///    &lt;spa [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string TraspasoSaldo {
            get {
                return ResourceManager.GetString("TraspasoSaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div style=&quot;padding: 0 20px&quot;&gt;
        ///  &lt;span style=&quot;margin-bottom: 0 !important; color: #a9a9a9; font-size: 1em&quot;
        ///    &gt;{0}&lt;/span
        ///  &gt;
        ///  &lt;h2
        ///    style=&quot;font-size: 1.5em; color: #333333; margin-top: 0; margin-bottom: 10px&quot;
        ///  &gt;
        ///    {1}
        ///  &lt;/h2&gt;
        ///  &lt;p style=&quot;font-size: 1em; color: #5e6d76&quot;&gt;
        ///    &lt;span style=&quot;font-weight: bold&quot;&gt;{4}, {Nombre}:&lt;/span&gt;&lt;br /&gt;
        ///    &lt;span&gt;{Mensaje}&lt;/span&gt;
        ///  &lt;/p&gt;
        ///  &lt;div style=&quot;border-top: 1px dashed #ededed; margin: 20px 0&quot;&gt;&lt;/div&gt;
        ///  &lt;p style=&quot;font-size: 1em; color: #5e6d76&quot;&gt;
        ///    &lt;spa [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string VentaSaldo {
            get {
                return ResourceManager.GetString("VentaSaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div style=&quot;padding: 0 20px&quot;&gt;
        ///  &lt;span style=&quot;margin-bottom: 0 !important; color: #a9a9a9; font-size: 1em&quot;&gt;
        ///    {0}
        ///  &lt;/span&gt;
        ///  &lt;h2
        ///    style=&quot;font-size: 1.5em; color: #333333; margin-top: 0; margin-bottom: 10px&quot;
        ///  &gt;
        ///    {1}
        ///  &lt;/h2&gt;
        ///  &lt;p style=&quot;font-size: 1em; color: #5e6d76&quot;&gt;
        ///    &lt;span style=&quot;font-weight: bold&quot;&gt;{5}, {Nombre}:&lt;/span&gt;&lt;br /&gt;
        ///    &lt;span&gt;{2}&lt;/span&gt;
        ///  &lt;/p&gt;
        ///  &lt;div style=&quot;border-top: 1px dashed #ededed; margin: 20px 0&quot;&gt;&lt;/div&gt;
        ///  &lt;p
        ///    style=&quot;
        ///      font-size: 2em;
        ///      color: #c922 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div style=&quot;padding: 0 20px&quot;&gt;
        ///    &lt;span style=&quot;margin-bottom: 0 !important; color: #a9a9a9; font-size: 1em&quot;&gt;
        ///        {0}
        ///    &lt;/span&gt;
        ///    &lt;h2 style=&quot;font-size: 2.5em; color: #333333; margin-top: 0; margin-bottom: 10px&quot;&gt;
        ///        {1}
        ///    &lt;/h2&gt;
        ///    &lt;p style=&quot;font-size: 1em; color: #5e6d76&quot;&gt;
        ///        &lt;span style=&quot;font-weight: bold&quot;&gt;{2}&lt;/span&gt;&lt;br /&gt;
        ///    &lt;/p&gt;
        ///    &lt;p style=&quot;font-size: 1em; color: #5e6d76&quot;&gt;
        ///        &lt;span&gt;{3}&lt;/span&gt;
        ///    &lt;/p&gt;
        ///
        ///    &lt;div style=&quot;border-top: 1px dashed #ededed; margin: 20px 0 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string VerificationCodeVigencia {
            get {
                return ResourceManager.GetString("VerificationCodeVigencia", resourceCulture);
            }
        }
    }
}
