apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
spec:
  selector:
    app: app-service
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort