//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMonederoCommand.Entities.Lenguajes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menssages_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menssages_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppMonederoCommand.Entities.Lenguajes.Menssages.es", typeof(Menssages_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se realizó un abono a la {TD} {0} por el importe de ${1} pesos..
        /// </summary>
        public static string BusAbonoMonedero {
            get {
                return ResourceManager.GetString("BusAbonoMonedero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuenta ya existe, intenta iniciar sesion a través de.
        /// </summary>
        public static string BusAccountExistSocial {
            get {
                return ResourceManager.GetString("BusAccountExistSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuenta está inactiva.
        /// </summary>
        public static string BusAccountInactive {
            get {
                return ResourceManager.GetString("BusAccountInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad de boletos solicitado es mayor a lo permitido..
        /// </summary>
        public static string BusAmountIsMayor {
            get {
                return ResourceManager.GetString("BusAmountIsMayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu saldo es insuficiente para esta operación. Recarga tu tarjeta y vuelve a intentar..
        /// </summary>
        public static string BusBoletoError100Saldo {
            get {
                return ResourceManager.GetString("BusBoletoError100Saldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad de tickets a generar es requerida..
        /// </summary>
        public static string BusBoletoError101NoCantidad {
            get {
                return ResourceManager.GetString("BusBoletoError101NoCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcanzaste el límite de tickets generados. Inténtalo con menos tickets..
        /// </summary>
        public static string BusBoletoError102MaxCantidad {
            get {
                return ResourceManager.GetString("BusBoletoError102MaxCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paquete no encontrado. Verifica e intenta de nuevo..
        /// </summary>
        public static string BusBoletoError103NoPaquete {
            get {
                return ResourceManager.GetString("BusBoletoError103NoPaquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paquete no vigente. Por favor revisa la fecha de vigencia..
        /// </summary>
        public static string BusBoletoError104VigenciaPaquete {
            get {
                return ResourceManager.GetString("BusBoletoError104VigenciaPaquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al generar el QR, intente de nuevo..
        /// </summary>
        public static string BusBoletoErrorService {
            get {
                return ResourceManager.GetString("BusBoletoErrorService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al cancelar el QR, intente de nuevo..
        /// </summary>
        public static string BusBoletoErrorServiceCancelation {
            get {
                return ResourceManager.GetString("BusBoletoErrorServiceCancelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo validar tu tarjeta inteligente, intenta de nuevo..
        /// </summary>
        public static string BusBoletoErrorValidaMonedero {
            get {
                return ResourceManager.GetString("BusBoletoErrorValidaMonedero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener tu saldo actual, intenta de nuevo..
        /// </summary>
        public static string BusBoletoErrorValidaSaldo {
            get {
                return ResourceManager.GetString("BusBoletoErrorValidaSaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo validar tu tarjeta, intenta de nuevo..
        /// </summary>
        public static string BusBoletoErrorValidaTarjeta {
            get {
                return ResourceManager.GetString("BusBoletoErrorValidaTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tarjeta .
        /// </summary>
        public static string BusCard {
            get {
                return ResourceManager.GetString("BusCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to esta bloqueada, valide la tarjeta.
        /// </summary>
        public static string BusCardBloq {
            get {
                return ResourceManager.GetString("BusCardBloq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to esta bloqueada:.
        /// </summary>
        public static string BusCardBloqSimple {
            get {
                return ResourceManager.GetString("BusCardBloqSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tarjeta de destino.
        /// </summary>
        public static string BusCardDestiny {
            get {
                return ResourceManager.GetString("BusCardDestiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to esta inactiva.
        /// </summary>
        public static string BusCardInactive {
            get {
                return ResourceManager.GetString("BusCardInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tarjeta de origen.
        /// </summary>
        public static string BusCardOrigin {
            get {
                return ResourceManager.GetString("BusCardOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tarjeta.
        /// </summary>
        public static string BusCardTransfer {
            get {
                return ResourceManager.GetString("BusCardTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu código de verificación es.
        /// </summary>
        public static string BusCodeVerification {
            get {
                return ResourceManager.GetString("BusCodeVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completado.
        /// </summary>
        public static string BusComplete {
            get {
                return ResourceManager.GetString("BusComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completado correctamente..
        /// </summary>
        public static string BusCompleteCorrect {
            get {
                return ResourceManager.GetString("BusCompleteCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correcto..
        /// </summary>
        public static string BusCorrecto {
            get {
                return ResourceManager.GetString("BusCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciales incorrectas..
        /// </summary>
        public static string BusCredentialIncorrect {
            get {
                return ResourceManager.GetString("BusCredentialIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciales incorrectas..
        /// </summary>
        public static string BusCredentialsIncorrect {
            get {
                return ResourceManager.GetString("BusCredentialsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURP no válido, la CURP ingresada ya está asociada a otro usuario.
        /// </summary>
        public static string BusCrupNoValid {
            get {
                return ResourceManager.GetString("BusCrupNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El siguiente dato es requerido.
        /// </summary>
        public static string BusDataRequired {
            get {
                return ResourceManager.GetString("BusDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los siguientes datos son requeridos.
        /// </summary>
        public static string BusDatasRequired {
            get {
                return ResourceManager.GetString("BusDatasRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo electrónico ingresado se encuentra asociado a una cuenta inactiva.
        /// </summary>
        public static string BusEmailInactiveAccount {
            get {
                return ResourceManager.GetString("BusEmailInactiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo no válido.
        /// </summary>
        public static string BusEmailNoValid {
            get {
                return ResourceManager.GetString("BusEmailNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo no válido, la cuenta de correo ingresada ya está asociada a otro usuario.
        /// </summary>
        public static string BusEmailNoValidAsociate {
            get {
                return ResourceManager.GetString("BusEmailNoValidAsociate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo no válido, verifique que esté escrito correctamente.
        /// </summary>
        public static string BusEmailNoValidExtended {
            get {
                return ResourceManager.GetString("BusEmailNoValidExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se requiere la cantidad de boletos a generar..
        /// </summary>
        public static string BusErrorCountTickets {
            get {
                return ResourceManager.GetString("BusErrorCountTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo de InfraTipo vacía.
        /// </summary>
        public static string BusFieldInfraType {
            get {
                return ResourceManager.GetString("BusFieldInfraType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo de Ruta vacía.
        /// </summary>
        public static string BusFieldRoute {
            get {
                return ResourceManager.GetString("BusFieldRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo de Unidad vacía.
        /// </summary>
        public static string BusFieldUnid {
            get {
                return ResourceManager.GetString("BusFieldUnid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Tipo, no es correcto.
        /// </summary>
        public static string BusFielType {
            get {
                return ResourceManager.GetString("BusFielType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to está bloqueado.
        /// </summary>
        public static string BusIsBloq {
            get {
                return ResourceManager.GetString("BusIsBloq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traspaso a tarjeta inteligente No:.
        /// </summary>
        public static string BusMessageTraspaso {
            get {
                return ResourceManager.GetString("BusMessageTraspaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tarjeta inteligente .
        /// </summary>
        public static string BusMonedero {
            get {
                return ResourceManager.GetString("BusMonedero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  esta bloqueado, valide la tarjeta inteligente .
        /// </summary>
        public static string BusMonederoBloqValid {
            get {
                return ResourceManager.GetString("BusMonederoBloqValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abordaje.
        /// </summary>
        public static string BusMonederoConceptoAbordaje {
            get {
                return ResourceManager.GetString("BusMonederoConceptoAbordaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconocido.
        /// </summary>
        public static string BusMonederoConceptoDesconocido {
            get {
                return ResourceManager.GetString("BusMonederoConceptoDesconocido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra de saldo.
        /// </summary>
        public static string BusMonederoConceptoSaldo {
            get {
                return ResourceManager.GetString("BusMonederoConceptoSaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra en CoDi.
        /// </summary>
        public static string BusMonederoConceptoSaldoCoDi {
            get {
                return ResourceManager.GetString("BusMonederoConceptoSaldoCoDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra en Mercado Pago.
        /// </summary>
        public static string BusMonederoConceptoSaldoMercadoPago {
            get {
                return ResourceManager.GetString("BusMonederoConceptoSaldoMercadoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra en Paypal.
        /// </summary>
        public static string BusMonederoConceptoSaldoPayPal {
            get {
                return ResourceManager.GetString("BusMonederoConceptoSaldoPayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra con tarjeta.
        /// </summary>
        public static string BusMonederoConceptoSaldoTarjeta {
            get {
                return ResourceManager.GetString("BusMonederoConceptoSaldoTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traspaso de tarjeta inteligente No. .
        /// </summary>
        public static string BusMonederoConceptoTraspasoAbono {
            get {
                return ResourceManager.GetString("BusMonederoConceptoTraspasoAbono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traspaso a tarjeta inteligente No. .
        /// </summary>
        public static string BusMonederoConceptoTraspasoCargo {
            get {
                return ResourceManager.GetString("BusMonederoConceptoTraspasoCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta de tarjeta.
        /// </summary>
        public static string BusMonederoConceptoVentaTarjeta {
            get {
                return ResourceManager.GetString("BusMonederoConceptoVentaTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta de ticket QR.
        /// </summary>
        public static string BusMonederoConceptoVentaTicket {
            get {
                return ResourceManager.GetString("BusMonederoConceptoVentaTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tarjeta inteligente destino .
        /// </summary>
        public static string BusMonederoDestiny {
            get {
                return ResourceManager.GetString("BusMonederoDestiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tarjeta inteligente origen .
        /// </summary>
        public static string BusMonederoOrigin {
            get {
                return ResourceManager.GetString("BusMonederoOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se creo correctamente el token.
        /// </summary>
        public static string BusNoAddCorrectToken {
            get {
                return ResourceManager.GetString("BusNoAddCorrectToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ya no esta disponible en el sistema.
        /// </summary>
        public static string BusNoAviableSytem {
            get {
                return ResourceManager.GetString("BusNoAviableSytem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no se encuentra correctamente configurada.
        /// </summary>
        public static string BusNoCorrectConfig {
            get {
                return ResourceManager.GetString("BusNoCorrectConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no se encuentra correctamente configurado el estatus.
        /// </summary>
        public static string BusNoCorrectStatusConfig {
            get {
                return ResourceManager.GetString("BusNoCorrectStatusConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la tarjeta inteligente..
        /// </summary>
        public static string BusNoExistMonedero {
            get {
                return ResourceManager.GetString("BusNoExistMonedero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se generó ningún boleto..
        /// </summary>
        public static string BusNoGenerateTicket {
            get {
                return ResourceManager.GetString("BusNoGenerateTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no tiene un motivo de bloqueo.
        /// </summary>
        public static string BusNoMotivoBloq {
            get {
                return ResourceManager.GetString("BusNoMotivoBloq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener el tipo de tarifa.
        /// </summary>
        public static string BusNoObtainTarifa {
            get {
                return ResourceManager.GetString("BusNoObtainTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin registros.
        /// </summary>
        public static string BusNoRegisters {
            get {
                return ResourceManager.GetString("BusNoRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin respuesta exitosa.
        /// </summary>
        public static string BusNoRespon {
            get {
                return ResourceManager.GetString("BusNoRespon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró historial..
        /// </summary>
        public static string BusNotfoundHistory {
            get {
                return ResourceManager.GetString("BusNotfoundHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiene boletos disponibles.
        /// </summary>
        public static string BusNoticketsAviables {
            get {
                return ResourceManager.GetString("BusNoticketsAviables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay tarjeta a validar.
        /// </summary>
        public static string BusNoValidCards {
            get {
                return ResourceManager.GetString("BusNoValidCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tarjeta inteligente no está asociada a un usuario..
        /// </summary>
        public static string BusOrderUserNoAuthorized {
            get {
                return ResourceManager.GetString("BusOrderUserNoAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña no coinciden, inténtelo de nuevo.
        /// </summary>
        public static string BusPasswordCoincide {
            get {
                return ResourceManager.GetString("BusPasswordCoincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no coinciden.
        /// </summary>
        public static string BusPasswordNoMacthes {
            get {
                return ResourceManager.GetString("BusPasswordNoMacthes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono no válido, el teléfono ingresado ya está asociada a otro usuario.
        /// </summary>
        public static string BusPhoneNoValid {
            get {
                return ResourceManager.GetString("BusPhoneNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error obtener plantilla.
        /// </summary>
        public static string BusPlantillaError {
            get {
                return ResourceManager.GetString("BusPlantillaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se requiere un correo electrónico para la recuperación de la cuenta..
        /// </summary>
        public static string BusRequiredEmailRestore {
            get {
                return ResourceManager.GetString("BusRequiredEmailRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es necesaria una imagen..
        /// </summary>
        public static string BusRequiredImage {
            get {
                return ResourceManager.GetString("BusRequiredImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede iniciar sesión, cuenta inactiva.
        /// </summary>
        public static string BusSessionFailInactive {
            get {
                return ResourceManager.GetString("BusSessionFailInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS enviado..
        /// </summary>
        public static string BusSMSSend {
            get {
                return ResourceManager.GetString("BusSMSSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha enviado una contraseña de acceso temporal a su cuenta de correo electrónico.
        /// </summary>
        public static string BusTemporalPass {
            get {
                return ResourceManager.GetString("BusTemporalPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña temporal ha caducado.
        /// </summary>
        public static string BusTemporalPassExpired {
            get {
                return ResourceManager.GetString("BusTemporalPassExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin respuesta exitosa del catálogo de Tipo Tarifa..
        /// </summary>
        public static string BusTipoTarifaFailed {
            get {
                return ResourceManager.GetString("BusTipoTarifaFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El token no es válido..
        /// </summary>
        public static string BusTokenNoValid {
            get {
                return ResourceManager.GetString("BusTokenNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario ya registrado, por favor inicie sesión..
        /// </summary>
        public static string BusUserAlreadyRegister {
            get {
                return ResourceManager.GetString("BusUserAlreadyRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no cuenta con una tarjeta inteligente..
        /// </summary>
        public static string BusUserNoMonedero {
            get {
                return ResourceManager.GetString("BusUserNoMonedero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se verificó correctamente el usuario.
        /// </summary>
        public static string BusUserNoVerify {
            get {
                return ResourceManager.GetString("BusUserNoVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no está autorizado para crear ordenes..
        /// </summary>
        public static string BusUserPaymets {
            get {
                return ResourceManager.GetString("BusUserPaymets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario a actualizar no existe..
        /// </summary>
        public static string BusUserUpdateNoExist {
            get {
                return ResourceManager.GetString("BusUserUpdateNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario se ha actualizado correctamente..
        /// </summary>
        public static string BusUserUpdateSuccess {
            get {
                return ResourceManager.GetString("BusUserUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha realizado un traspaso de ${0} pesos de la {TO} {1} a la {TD} {2}.
        /// </summary>
        public static string BusUsuarioMensajeNotificacionTraspaso {
            get {
                return ResourceManager.GetString("BusUsuarioMensajeNotificacionTraspaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificación.
        /// </summary>
        public static string BusUsuarioMensajeNotificacionTraspasoTitulo {
            get {
                return ResourceManager.GetString("BusUsuarioMensajeNotificacionTraspasoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valide que la contraseña contenga al menos un número y letra, sin espacios, también tenga de 8 a 250 caracteres.
        /// </summary>
        public static string BusValidatePassword {
            get {
                return ResourceManager.GetString("BusValidatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor del parámetro de cantidad máxima de boletos a crear no es un número válido..
        /// </summary>
        public static string BusValueNoValidTickets {
            get {
                return ResourceManager.GetString("BusValueNoValidTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifica los datos de la tarjeta..
        /// </summary>
        public static string BusVerificatedCard {
            get {
                return ResourceManager.GetString("BusVerificatedCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifica tus credenciales de acceso.
        /// </summary>
        public static string BusVerifiCredentials {
            get {
                return ResourceManager.GetString("BusVerifiCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tarjeta inteligente.
        /// </summary>
        public static string BusWalledTransfer {
            get {
                return ResourceManager.GetString("BusWalledTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuenta no existe.
        /// </summary>
        public static string DatAccountNoExits {
            get {
                return ResourceManager.GetString("DatAccountNoExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta no recuperada.
        /// </summary>
        public static string DatAccountNoRecovered {
            get {
                return ResourceManager.GetString("DatAccountNoRecovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuenta solicitada para recuperación no existe..
        /// </summary>
        public static string DatAccountSolicitadeNoExits {
            get {
                return ResourceManager.GetString("DatAccountSolicitadeNoExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parámetro se agregó correctamente..
        /// </summary>
        public static string DatAddSuccesParameter {
            get {
                return ResourceManager.GetString("DatAddSuccesParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No completado correctamente..
        /// </summary>
        public static string DatCompleteFailed {
            get {
                return ResourceManager.GetString("DatCompleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completado correctamente..
        /// </summary>
        public static string DatCompleteSucces {
            get {
                return ResourceManager.GetString("DatCompleteSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro no eliminado.
        /// </summary>
        public static string DatDeleteFailed {
            get {
                return ResourceManager.GetString("DatDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminado correctamente.
        /// </summary>
        public static string DatDeleteSucess {
            get {
                return ResourceManager.GetString("DatDeleteSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se desactivaron todos los RefreshToken..
        /// </summary>
        public static string DatDesactivateTokens {
            get {
                return ResourceManager.GetString("DatDesactivateTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error inesperado.
        /// </summary>
        public static string DatErrorGeneric {
            get {
                return ResourceManager.GetString("DatErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error desconocido, no se pudo guardar el token de recuperación.
        /// </summary>
        public static string DatErrorTokenRecover {
            get {
                return ResourceManager.GetString("DatErrorTokenRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las ubicaciones se obtuvieron correctamente..
        /// </summary>
        public static string DatGetLocatiosSucces {
            get {
                return ResourceManager.GetString("DatGetLocatiosSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los parámetros se obtuvieron correctamente..
        /// </summary>
        public static string DatGetSuccesParameter {
            get {
                return ResourceManager.GetString("DatGetSuccesParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ubicacion favorita no existe.
        /// </summary>
        public static string DatLocationFavoriteNoExist {
            get {
                return ResourceManager.GetString("DatLocationFavoriteNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación no registrada.
        /// </summary>
        public static string DatLocationNoRegistered {
            get {
                return ResourceManager.GetString("DatLocationNoRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se agregó el parámetro..
        /// </summary>
        public static string DatNoAddParameter {
            get {
                return ResourceManager.GetString("DatNoAddParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugerencia no registrada.
        /// </summary>
        public static string DatNoAddSuggestion {
            get {
                return ResourceManager.GetString("DatNoAddSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay cambios para guardar.
        /// </summary>
        public static string DatNoChanges {
            get {
                return ResourceManager.GetString("DatNoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen boletos disponibles..
        /// </summary>
        public static string DatNoExistBoleto {
            get {
                return ResourceManager.GetString("DatNoExistBoleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen ubicaciones favoritas..
        /// </summary>
        public static string DatNoExistFavoriteUbications {
            get {
                return ResourceManager.GetString("DatNoExistFavoriteUbications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen parámetros..
        /// </summary>
        public static string DatNoExistParameters {
            get {
                return ResourceManager.GetString("DatNoExistParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe registro..
        /// </summary>
        public static string DatNoExistRegister {
            get {
                return ResourceManager.GetString("DatNoExistRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el registro para eliminar..
        /// </summary>
        public static string DatNoExistRegisterDelete {
            get {
                return ResourceManager.GetString("DatNoExistRegisterDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parametro a actualizar no existe..
        /// </summary>
        public static string DatNoExistUpdateParameter {
            get {
                return ResourceManager.GetString("DatNoExistUpdateParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró al usuario con la cuenta verificada..
        /// </summary>
        public static string DatNoExistUserVerificated {
            get {
                return ResourceManager.GetString("DatNoExistUserVerificated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el registro..
        /// </summary>
        public static string DatNoGetRegister {
            get {
                return ResourceManager.GetString("DatNoGetRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo agregar al historia de refresh token..
        /// </summary>
        public static string DatNoHistoryRefresToken {
            get {
                return ResourceManager.GetString("DatNoHistoryRefresToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiene RefreshToken asociados..
        /// </summary>
        public static string DatNoRefreshTokens {
            get {
                return ResourceManager.GetString("DatNoRefreshTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el registro para el token solicitado..
        /// </summary>
        public static string DatNoRegisteredToken {
            get {
                return ResourceManager.GetString("DatNoRegisteredToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos no guardados.
        /// </summary>
        public static string DatNoSave {
            get {
                return ResourceManager.GetString("DatNoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo actualizar el código verificación..
        /// </summary>
        public static string DatNoUpdateCodeVerification {
            get {
                return ResourceManager.GetString("DatNoUpdateCodeVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el registro para actualizar..
        /// </summary>
        public static string DatNoUpdateExist {
            get {
                return ResourceManager.GetString("DatNoUpdateExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se actualizó el parámetro..
        /// </summary>
        public static string DatNoUpdateParameter {
            get {
                return ResourceManager.GetString("DatNoUpdateParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo actualizar la contraseña, el proceso ya fue finalizado o expiro el tiempo dado para el cambio de contraseña..
        /// </summary>
        public static string DatNoUpdatePassword {
            get {
                return ResourceManager.GetString("DatNoUpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo actualizar el estatus de verificación de la cuenta..
        /// </summary>
        public static string DatNoUseStatusAccount {
            get {
                return ResourceManager.GetString("DatNoUseStatusAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error.
        /// </summary>
        public static string DatOcurredError {
            get {
                return ResourceManager.GetString("DatOcurredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parámetro.
        /// </summary>
        public static string DatParameterCompuest1 {
            get {
                return ResourceManager.GetString("DatParameterCompuest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no existe..
        /// </summary>
        public static string DatParameterCompuest2 {
            get {
                return ResourceManager.GetString("DatParameterCompuest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La nueva contraseña debe ser diferente a la anterior..
        /// </summary>
        public static string DatPasswordDiferent {
            get {
                return ResourceManager.GetString("DatPasswordDiferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña  aleatoria debe ser diferente a la anterior..
        /// </summary>
        public static string DatPasswordRandom {
            get {
                return ResourceManager.GetString("DatPasswordRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tarjeta inteligente no cambió.
        /// </summary>
        public static string DatPurseNoChanges {
            get {
                return ResourceManager.GetString("DatPurseNoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya está vinculada..
        /// </summary>
        public static string DatRegisteredCard {
            get {
                return ResourceManager.GetString("DatRegisteredCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro no existe.
        /// </summary>
        public static string DatRegisterNoExist {
            get {
                return ResourceManager.GetString("DatRegisterNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parámetro se actualizó correctamente..
        /// </summary>
        public static string DatSuccesUpdateParameter {
            get {
                return ResourceManager.GetString("DatSuccesUpdateParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A caducado el tiempo para la recuperación de la cuenta, inténtelo nuevamente..
        /// </summary>
        public static string DatTimeOutAccount {
            get {
                return ResourceManager.GetString("DatTimeOutAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tiempo de espera para la recuperación ya había terminado, inténtelo nuevamente.
        /// </summary>
        public static string DatTimeTerminateAccount {
            get {
                return ResourceManager.GetString("DatTimeTerminateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El toquen ya está inactivo..
        /// </summary>
        public static string DatTokenInactive {
            get {
                return ResourceManager.GetString("DatTokenInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token no almacenado.
        /// </summary>
        public static string DatTokenNoSave {
            get {
                return ResourceManager.GetString("DatTokenNoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los tokens enviados no son válidos..
        /// </summary>
        public static string DatTokenNoValids {
            get {
                return ResourceManager.GetString("DatTokenNoValids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los tokens se obtuvieron correctamente..
        /// </summary>
        public static string DatTokensSucess {
            get {
                return ResourceManager.GetString("DatTokensSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token utilizado.
        /// </summary>
        public static string DatTokenUsed {
            get {
                return ResourceManager.GetString("DatTokenUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registró no actualizado.
        /// </summary>
        public static string DatUpdateFailed {
            get {
                return ResourceManager.GetString("DatUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizado correctamente.
        /// </summary>
        public static string DatUpdateSucces {
            get {
                return ResourceManager.GetString("DatUpdateSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no encontrado.
        /// </summary>
        public static string DatUserNoExist {
            get {
                return ResourceManager.GetString("DatUserNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario solicitado no está disponible..
        /// </summary>
        public static string DatUserSolicitadeNoAviable {
            get {
                return ResourceManager.GetString("DatUserSolicitadeNoAviable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registró no verificado.
        /// </summary>
        public static string DatVerificateFailed {
            get {
                return ResourceManager.GetString("DatVerificateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificado correctamente.
        /// </summary>
        public static string DatVerificateSucces {
            get {
                return ResourceManager.GetString("DatVerificateSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifica tu correo electrónico.
        /// </summary>
        public static string DatVerifyEmail {
            get {
                return ResourceManager.GetString("DatVerifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to solo estará disponible 48 hrs..
        /// </summary>
        public static string Html48Hours {
            get {
                return ResourceManager.GetString("Html48Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto.
        /// </summary>
        public static string HtmlAmount {
            get {
                return ResourceManager.GetString("HtmlAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicación de transporte.
        /// </summary>
        public static string HtmlAplicateTransport {
            get {
                return ResourceManager.GetString("HtmlAplicateTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a la aplicación de transporte.
        /// </summary>
        public static string HtmlAppTransporte {
            get {
                return ResourceManager.GetString("HtmlAppTransporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra de saldo.
        /// </summary>
        public static string HtmlBalancePurchase {
            get {
                return ResourceManager.GetString("HtmlBalancePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentario.
        /// </summary>
        public static string HtmlComent {
            get {
                return ResourceManager.GetString("HtmlComent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto.
        /// </summary>
        public static string HtmlConcept {
            get {
                return ResourceManager.GetString("HtmlConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo de confirmación.
        /// </summary>
        public static string HtmlConfirmationEmail {
            get {
                return ResourceManager.GetString("HtmlConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string HtmlContact {
            get {
                return ResourceManager.GetString("HtmlContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string HtmlDate {
            get {
                return ResourceManager.GetString("HtmlDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha y hora.
        /// </summary>
        public static string HtmlDateAndTime {
            get {
                return ResourceManager.GetString("HtmlDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tu petición de la eliminación de cuenta.
        /// </summary>
        public static string HtmlDelAccount {
            get {
                return ResourceManager.GetString("HtmlDelAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta eliminada.
        /// </summary>
        public static string HtmlDeletedAccount {
            get {
                return ResourceManager.GetString("HtmlDeletedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y hemos procedido a borrar tus datos e información relacionada con tu perfil, accesos y registro. No es necesario realizar ninguna otra acción..
        /// </summary>
        public static string HtmlDelInfo {
            get {
                return ResourceManager.GetString("HtmlDelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to destino.
        /// </summary>
        public static string HtmlDestiny {
            get {
                return ResourceManager.GetString("HtmlDestiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to También puedes descargar la aplicación en:.
        /// </summary>
        public static string HtmlDownloadApp {
            get {
                return ResourceManager.GetString("HtmlDownloadApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gobierno del Estado de Yucatán.
        /// </summary>
        public static string HtmlGob {
            get {
                return ResourceManager.GetString("HtmlGob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saludos.
        /// </summary>
        public static string HtmlGreetings {
            get {
                return ResourceManager.GetString("HtmlGreetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola.
        /// </summary>
        public static string HtmlHello {
            get {
                return ResourceManager.GetString("HtmlHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORTANTE.
        /// </summary>
        public static string HtmlImportant {
            get {
                return ResourceManager.GetString("HtmlImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En caso de no haber realizado la operación indicada en esta confirmación, contacta a un representante de atención a clientes marcando al {telefono} o envía un correo electrónico a {email} y proporciona el número de folio..
        /// </summary>
        public static string HtmlImportantLabel {
            get {
                return ResourceManager.GetString("HtmlImportantLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información.
        /// </summary>
        public static string HtmlInfo {
            get {
                return ResourceManager.GetString("HtmlInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este correo es informativo, por favor no respondas, no está habilitado para recibir mensajes..
        /// </summary>
        public static string HtmlInfoEmail {
            get {
                return ResourceManager.GetString("HtmlInfoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo infraestructura.
        /// </summary>
        public static string HtmlInfraType {
            get {
                return ResourceManager.GetString("HtmlInfraType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es.
        /// </summary>
        public static string HtmlIs {
            get {
                return ResourceManager.GetString("HtmlIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Contraseña.
        /// </summary>
        public static string HtmlNewPass {
            get {
                return ResourceManager.GetString("HtmlNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles de la operación.
        /// </summary>
        public static string HtmlOperationDetails {
            get {
                return ResourceManager.GetString("HtmlOperationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folio de la operación.
        /// </summary>
        public static string HtmlOperationFolio {
            get {
                return ResourceManager.GetString("HtmlOperationFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to origen.
        /// </summary>
        public static string HtmlOrigin {
            get {
                return ResourceManager.GetString("HtmlOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to que lo hagas, ya que de lo contrario no podrás iniciar sesión en la aplicación. También puedes recuperarla copiando y pegando el siguiente link en tu navegador..
        /// </summary>
        public static string HtmlPassWarning {
            get {
                return ResourceManager.GetString("HtmlPassWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recupera tu contraseña.
        /// </summary>
        public static string HtmlRecoverYourPassword {
            get {
                return ResourceManager.GetString("HtmlRecoverYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Tu registro se ha finalizado con éxito!.
        /// </summary>
        public static string HtmlRegisterSuccess {
            get {
                return ResourceManager.GetString("HtmlRegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te recordamos tu número de folio:.
        /// </summary>
        public static string HtmlRemember {
            get {
                return ResourceManager.GetString("HtmlRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te recordamos acceder y cambiar tu contraseña. La que te compartimos es temporal y.
        /// </summary>
        public static string HtmlRememberPass {
            get {
                return ResourceManager.GetString("HtmlRememberPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has solicitado recuperar la contraseña de tu cuenta. Para asignar una nueva contraseña haz clic en el siguiente botón..
        /// </summary>
        public static string HtmlRePassInfo {
            get {
                return ResourceManager.GetString("HtmlRePassInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte.
        /// </summary>
        public static string HtmlReport {
            get {
                return ResourceManager.GetString("HtmlReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportado por.
        /// </summary>
        public static string HtmlReportedBy {
            get {
                return ResourceManager.GetString("HtmlReportedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte de incidencia.
        /// </summary>
        public static string HtmlReportIncide {
            get {
                return ResourceManager.GetString("HtmlReportIncide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta.
        /// </summary>
        public static string HtmlRoute {
            get {
                return ResourceManager.GetString("HtmlRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te enviamos tu código de verificación.
        /// </summary>
        public static string HtmlSendCode {
            get {
                return ResourceManager.GetString("HtmlSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te enviamos la contraseña para que puedas acceder..
        /// </summary>
        public static string HtmlSendTemporalPass {
            get {
                return ResourceManager.GetString("HtmlSendTemporalPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña temporal.
        /// </summary>
        public static string HtmlTemporalPassword {
            get {
                return ResourceManager.GetString("HtmlTemporalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traspaso.
        /// </summary>
        public static string HtmlTransfer {
            get {
                return ResourceManager.GetString("HtmlTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string HtmlType {
            get {
                return ResourceManager.GetString("HtmlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad.
        /// </summary>
        public static string HtmlUnid {
            get {
                return ResourceManager.GetString("HtmlUnid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemos recibido.
        /// </summary>
        public static string HtmlUsReceived {
            get {
                return ResourceManager.GetString("HtmlUsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido/a.
        /// </summary>
        public static string HtmlWelcome {
            get {
                return ResourceManager.GetString("HtmlWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenguaje no valido.
        /// </summary>
        public static string WebLenguajeNoValid {
            get {
                return ResourceManager.GetString("WebLenguajeNoValid", resourceCulture);
            }
        }
    }
}
