//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMonederoCommand.Entities.Lenguajes {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menssages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menssages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppMonederoCommand.Entities.Lenguajes.Menssages", typeof(Menssages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A credit was made to the {TD} {0} for the amount of ${1}.
        /// </summary>
        public static string BusAbonoMonedero {
            get {
                return ResourceManager.GetString("BusAbonoMonedero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account already exists, try to log in through.
        /// </summary>
        public static string BusAccountExistSocial {
            get {
                return ResourceManager.GetString("BusAccountExistSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account is inactive.
        /// </summary>
        public static string BusAccountInactive {
            get {
                return ResourceManager.GetString("BusAccountInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The number of tickets requested is greater than allowed..
        /// </summary>
        public static string BusAmountIsMayor {
            get {
                return ResourceManager.GetString("BusAmountIsMayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your session has been closed due to account blocking..
        /// </summary>
        public static string BusBlockedAccountApp {
            get {
                return ResourceManager.GetString("BusBlockedAccountApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your balance is insufficient for this service. Please recharge your card and try again..
        /// </summary>
        public static string BusBoletoError100Saldo {
            get {
                return ResourceManager.GetString("BusBoletoError100Saldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The number of tickets to generate is required...
        /// </summary>
        public static string BusBoletoError101NoCantidad {
            get {
                return ResourceManager.GetString("BusBoletoError101NoCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have reached the maximum number of tickets allowed. Please try again with fewer tickets..
        /// </summary>
        public static string BusBoletoError102MaxCantidad {
            get {
                return ResourceManager.GetString("BusBoletoError102MaxCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package not found. Please verify and try again..
        /// </summary>
        public static string BusBoletoError103NoPaquete {
            get {
                return ResourceManager.GetString("BusBoletoError103NoPaquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package is not valid. Please check the expiration date..
        /// </summary>
        public static string BusBoletoError104VigenciaPaquete {
            get {
                return ResourceManager.GetString("BusBoletoError104VigenciaPaquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while generating your ticket QR. Please try again..
        /// </summary>
        public static string BusBoletoErrorService {
            get {
                return ResourceManager.GetString("BusBoletoErrorService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while canceling your ticket QR. Please try again..
        /// </summary>
        public static string BusBoletoErrorServiceCancelation {
            get {
                return ResourceManager.GetString("BusBoletoErrorServiceCancelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your wallet could not be validated. Please try again..
        /// </summary>
        public static string BusBoletoErrorValidaMonedero {
            get {
                return ResourceManager.GetString("BusBoletoErrorValidaMonedero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your current balance could not be retrieved. Please try again..
        /// </summary>
        public static string BusBoletoErrorValidaSaldo {
            get {
                return ResourceManager.GetString("BusBoletoErrorValidaSaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your card could not be validated. Please try again..
        /// </summary>
        public static string BusBoletoErrorValidaTarjeta {
            get {
                return ResourceManager.GetString("BusBoletoErrorValidaTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The card -.
        /// </summary>
        public static string BusCard {
            get {
                return ResourceManager.GetString("BusCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is blocked, validate the card.
        /// </summary>
        public static string BusCardBloq {
            get {
                return ResourceManager.GetString("BusCardBloq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It&apos;s blocked:.
        /// </summary>
        public static string BusCardBloqSimple {
            get {
                return ResourceManager.GetString("BusCardBloqSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The destiny card.
        /// </summary>
        public static string BusCardDestiny {
            get {
                return ResourceManager.GetString("BusCardDestiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a is inactive.
        /// </summary>
        public static string BusCardInactive {
            get {
                return ResourceManager.GetString("BusCardInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The origin card.
        /// </summary>
        public static string BusCardOrigin {
            get {
                return ResourceManager.GetString("BusCardOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a card.
        /// </summary>
        public static string BusCardTransfer {
            get {
                return ResourceManager.GetString("BusCardTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your verification code is.
        /// </summary>
        public static string BusCodeVerification {
            get {
                return ResourceManager.GetString("BusCodeVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completed.
        /// </summary>
        public static string BusComplete {
            get {
                return ResourceManager.GetString("BusComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completed correctly..
        /// </summary>
        public static string BusCompleteCorrect {
            get {
                return ResourceManager.GetString("BusCompleteCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password Confirmation.
        /// </summary>
        public static string BusConfirmPass {
            get {
                return ResourceManager.GetString("BusConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correct..
        /// </summary>
        public static string BusCorrecto {
            get {
                return ResourceManager.GetString("BusCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect credentials..
        /// </summary>
        public static string BusCredentialIncorrect {
            get {
                return ResourceManager.GetString("BusCredentialIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect credentials..
        /// </summary>
        public static string BusCredentialsIncorrect {
            get {
                return ResourceManager.GetString("BusCredentialsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid CURP, the CURP entered is already associated with another user.
        /// </summary>
        public static string BusCrupNoValid {
            get {
                return ResourceManager.GetString("BusCrupNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The following information is required.
        /// </summary>
        public static string BusDataRequired {
            get {
                return ResourceManager.GetString("BusDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The following data is required.
        /// </summary>
        public static string BusDatasRequired {
            get {
                return ResourceManager.GetString("BusDatasRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Birthdate.
        /// </summary>
        public static string BusDateBorn {
            get {
                return ResourceManager.GetString("BusDateBorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-Mail.
        /// </summary>
        public static string BusEmail {
            get {
                return ResourceManager.GetString("BusEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email entered is associated with an inactive account.
        /// </summary>
        public static string BusEmailInactiveAccount {
            get {
                return ResourceManager.GetString("BusEmailInactiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid email.
        /// </summary>
        public static string BusEmailNoValid {
            get {
                return ResourceManager.GetString("BusEmailNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid email, the email account entered is already associated with another user.
        /// </summary>
        public static string BusEmailNoValidAsociate {
            get {
                return ResourceManager.GetString("BusEmailNoValidAsociate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid email, check if it is spelled correctly.
        /// </summary>
        public static string BusEmailNoValidExtended {
            get {
                return ResourceManager.GetString("BusEmailNoValidExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The number of tickets to be generated is required..
        /// </summary>
        public static string BusErrorCountTickets {
            get {
                return ResourceManager.GetString("BusErrorCountTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error getting virtual card..
        /// </summary>
        public static string BusErrorGetMonedero {
            get {
                return ResourceManager.GetString("BusErrorGetMonedero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was a problem generating your Wallet:.
        /// </summary>
        public static string BusFailedWallet {
            get {
                return ResourceManager.GetString("BusFailedWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a InfraTipo field empty.
        /// </summary>
        public static string BusFieldInfraType {
            get {
                return ResourceManager.GetString("BusFieldInfraType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empty Route field.
        /// </summary>
        public static string BusFieldRoute {
            get {
                return ResourceManager.GetString("BusFieldRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empty Unit Field.
        /// </summary>
        public static string BusFieldUnid {
            get {
                return ResourceManager.GetString("BusFieldUnid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type field, not correct.
        /// </summary>
        public static string BusFielType {
            get {
                return ResourceManager.GetString("BusFielType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gender.
        /// </summary>
        public static string BusGenero {
            get {
                return ResourceManager.GetString("BusGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a is blocked.
        /// </summary>
        public static string BusIsBloq {
            get {
                return ResourceManager.GetString("BusIsBloq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mother&apos;s last name.
        /// </summary>
        public static string BusLastNameM {
            get {
                return ResourceManager.GetString("BusLastNameM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name.
        /// </summary>
        public static string BusLastNameP {
            get {
                return ResourceManager.GetString("BusLastNameP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are logged in on another device, so this session will be closed..
        /// </summary>
        public static string BusLoginOtherDevice {
            get {
                return ResourceManager.GetString("BusLoginOtherDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have been logged out because you logged in on another device..
        /// </summary>
        public static string BusLogoutOtherDevice {
            get {
                return ResourceManager.GetString("BusLogoutOtherDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transfer to Wallet No. :.
        /// </summary>
        public static string BusMessageTraspaso {
            get {
                return ResourceManager.GetString("BusMessageTraspaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The wallet .
        /// </summary>
        public static string BusMonedero {
            get {
                return ResourceManager.GetString("BusMonedero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  It is blocked, validate the wallet .
        /// </summary>
        public static string BusMonederoBloqValid {
            get {
                return ResourceManager.GetString("BusMonederoBloqValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Boarding.
        /// </summary>
        public static string BusMonederoConceptoAbordaje {
            get {
                return ResourceManager.GetString("BusMonederoConceptoAbordaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown.
        /// </summary>
        public static string BusMonederoConceptoDesconocido {
            get {
                return ResourceManager.GetString("BusMonederoConceptoDesconocido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wallet recharge.
        /// </summary>
        public static string BusMonederoConceptoSaldo {
            get {
                return ResourceManager.GetString("BusMonederoConceptoSaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CoDi purchase.
        /// </summary>
        public static string BusMonederoConceptoSaldoCoDi {
            get {
                return ResourceManager.GetString("BusMonederoConceptoSaldoCoDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mercado Pago Purchase.
        /// </summary>
        public static string BusMonederoConceptoSaldoMercadoPago {
            get {
                return ResourceManager.GetString("BusMonederoConceptoSaldoMercadoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paypal Purchase.
        /// </summary>
        public static string BusMonederoConceptoSaldoPayPal {
            get {
                return ResourceManager.GetString("BusMonederoConceptoSaldoPayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debit/Credit card purchase.
        /// </summary>
        public static string BusMonederoConceptoSaldoTarjeta {
            get {
                return ResourceManager.GetString("BusMonederoConceptoSaldoTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transfer of Wallet.
        /// </summary>
        public static string BusMonederoConceptoTraspasoAbono {
            get {
                return ResourceManager.GetString("BusMonederoConceptoTraspasoAbono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transfer to Wallet.
        /// </summary>
        public static string BusMonederoConceptoTraspasoCargo {
            get {
                return ResourceManager.GetString("BusMonederoConceptoTraspasoCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Card sale.
        /// </summary>
        public static string BusMonederoConceptoVentaTarjeta {
            get {
                return ResourceManager.GetString("BusMonederoConceptoVentaTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ticket QR Sale.
        /// </summary>
        public static string BusMonederoConceptoVentaTicket {
            get {
                return ResourceManager.GetString("BusMonederoConceptoVentaTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The destination wallet .
        /// </summary>
        public static string BusMonederoDestiny {
            get {
                return ResourceManager.GetString("BusMonederoDestiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The original wallet .
        /// </summary>
        public static string BusMonederoOrigin {
            get {
                return ResourceManager.GetString("BusMonederoOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string BusName {
            get {
                return ResourceManager.GetString("BusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The token was not created correctly.
        /// </summary>
        public static string BusNoAddCorrectToken {
            get {
                return ResourceManager.GetString("BusNoAddCorrectToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is no longer available in the system.
        /// </summary>
        public static string BusNoAviableSytem {
            get {
                return ResourceManager.GetString("BusNoAviableSytem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a is not correctly configured.
        /// </summary>
        public static string BusNoCorrectConfig {
            get {
                return ResourceManager.GetString("BusNoCorrectConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a the status is not correctly configured.
        /// </summary>
        public static string BusNoCorrectStatusConfig {
            get {
                return ResourceManager.GetString("BusNoCorrectStatusConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron datos del monedero..
        /// </summary>
        public static string BusNoDatsMoney {
            get {
                return ResourceManager.GetString("BusNoDatsMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The wallet was not found..
        /// </summary>
        public static string BusNoExistMonedero {
            get {
                return ResourceManager.GetString("BusNoExistMonedero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ticket was generated..
        /// </summary>
        public static string BusNoGenerateTicket {
            get {
                return ResourceManager.GetString("BusNoGenerateTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can&apos;t log in because you&apos;ve already logged in from another device..
        /// </summary>
        public static string BusNoLogin {
            get {
                return ResourceManager.GetString("BusNoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a does not have a blocking reason.
        /// </summary>
        public static string BusNoMotivoBloq {
            get {
                return ResourceManager.GetString("BusNoMotivoBloq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not get rate type.
        /// </summary>
        public static string BusNoObtainTarifa {
            get {
                return ResourceManager.GetString("BusNoObtainTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No records.
        /// </summary>
        public static string BusNoRegisters {
            get {
                return ResourceManager.GetString("BusNoRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No successful response.
        /// </summary>
        public static string BusNoRespon {
            get {
                return ResourceManager.GetString("BusNoRespon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No history found..
        /// </summary>
        public static string BusNotfoundHistory {
            get {
                return ResourceManager.GetString("BusNotfoundHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are no tickets available.
        /// </summary>
        public static string BusNoticketsAviables {
            get {
                return ResourceManager.GetString("BusNoticketsAviables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The rate type was not found for the selected wallet..
        /// </summary>
        public static string BusNoTypeTarifaForMoney {
            get {
                return ResourceManager.GetString("BusNoTypeTarifaForMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is no card to validate.
        /// </summary>
        public static string BusNoValidCards {
            get {
                return ResourceManager.GetString("BusNoValidCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The wallet is not associated with a user..
        /// </summary>
        public static string BusOrderUserNoAuthorized {
            get {
                return ResourceManager.GetString("BusOrderUserNoAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password associated with the user has expired..
        /// </summary>
        public static string BusPassUserExpired {
            get {
                return ResourceManager.GetString("BusPassUserExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string BusPassword {
            get {
                return ResourceManager.GetString("BusPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password does not match, please try again.
        /// </summary>
        public static string BusPasswordCoincide {
            get {
                return ResourceManager.GetString("BusPasswordCoincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not match.
        /// </summary>
        public static string BusPasswordNoMacthes {
            get {
                return ResourceManager.GetString("BusPasswordNoMacthes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid phone number, the phone number entered is already associated with another user.
        /// </summary>
        public static string BusPhoneNoValid {
            get {
                return ResourceManager.GetString("BusPhoneNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error get template.
        /// </summary>
        public static string BusPlantillaError {
            get {
                return ResourceManager.GetString("BusPlantillaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cannot log in because the account has been reported..
        /// </summary>
        public static string BusReportedAccount {
            get {
                return ResourceManager.GetString("BusReportedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An email is required for account recovery..
        /// </summary>
        public static string BusRequiredEmailRestore {
            get {
                return ResourceManager.GetString("BusRequiredEmailRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An image is necessary..
        /// </summary>
        public static string BusRequiredImage {
            get {
                return ResourceManager.GetString("BusRequiredImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The refresh token is required..
        /// </summary>
        public static string BusRequiredRefreshToken {
            get {
                return ResourceManager.GetString("BusRequiredRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expired token is required..
        /// </summary>
        public static string BusRequiredTokenExpired {
            get {
                return ResourceManager.GetString("BusRequiredTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can&apos;t log in, account inactive.
        /// </summary>
        public static string BusSessionFailInactive {
            get {
                return ResourceManager.GetString("BusSessionFailInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SMS sent..
        /// </summary>
        public static string BusSMSSend {
            get {
                return ResourceManager.GetString("BusSMSSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a successful..
        /// </summary>
        public static string BusSuccesss {
            get {
                return ResourceManager.GetString("BusSuccesss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A temporary access password has been sent to your email account.
        /// </summary>
        public static string BusTemporalPass {
            get {
                return ResourceManager.GetString("BusTemporalPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temporary password has expired.
        /// </summary>
        public static string BusTemporalPassExpired {
            get {
                return ResourceManager.GetString("BusTemporalPassExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No successful response from the Rate Type catalogue..
        /// </summary>
        public static string BusTipoTarifaFailed {
            get {
                return ResourceManager.GetString("BusTipoTarifaFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log out..
        /// </summary>
        public static string BusTitleLogout {
            get {
                return ResourceManager.GetString("BusTitleLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The token is invalid..
        /// </summary>
        public static string BusTokenNoValid {
            get {
                return ResourceManager.GetString("BusTokenNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Already registered user, please log in..
        /// </summary>
        public static string BusUserAlreadyRegister {
            get {
                return ResourceManager.GetString("BusUserAlreadyRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user does not have a wallet..
        /// </summary>
        public static string BusUserNoMonedero {
            get {
                return ResourceManager.GetString("BusUserNoMonedero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User was not verified correctly.
        /// </summary>
        public static string BusUserNoVerify {
            get {
                return ResourceManager.GetString("BusUserNoVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user is not authorized to create the order..
        /// </summary>
        public static string BusUserPaymets {
            get {
                return ResourceManager.GetString("BusUserPaymets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The User associated with the RefreshToken is deleted..
        /// </summary>
        public static string BusUserRefreshTokenDel {
            get {
                return ResourceManager.GetString("BusUserRefreshTokenDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The User associated with the RefreshToken is inactive..
        /// </summary>
        public static string BusUserRefreshTokenInactive {
            get {
                return ResourceManager.GetString("BusUserRefreshTokenInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The User associated with the refreshtoken does not exist.
        /// </summary>
        public static string BusUserRefreshTokennoExits {
            get {
                return ResourceManager.GetString("BusUserRefreshTokennoExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user to update does not exist..
        /// </summary>
        public static string BusUserUpdateNoExist {
            get {
                return ResourceManager.GetString("BusUserUpdateNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user has been successfully updated..
        /// </summary>
        public static string BusUserUpdateSuccess {
            get {
                return ResourceManager.GetString("BusUserUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A transfer of ${0} has been completed from {TO} {1} to {TD} {2}.
        /// </summary>
        public static string BusUsuarioMensajeNotificacionTraspaso {
            get {
                return ResourceManager.GetString("BusUsuarioMensajeNotificacionTraspaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notification.
        /// </summary>
        public static string BusUsuarioMensajeNotificacionTraspasoTitulo {
            get {
                return ResourceManager.GetString("BusUsuarioMensajeNotificacionTraspasoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validate that the password contains at least one number and letter, without spaces, and also has 8 to 250 characters.
        /// </summary>
        public static string BusValidatePassword {
            get {
                return ResourceManager.GetString("BusValidatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value of the maximum number of tickets to create parameter is not a valid number..
        /// </summary>
        public static string BusValueNoValidTickets {
            get {
                return ResourceManager.GetString("BusValueNoValidTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify the card details..
        /// </summary>
        public static string BusVerificatedCard {
            get {
                return ResourceManager.GetString("BusVerificatedCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify your access credentials.
        /// </summary>
        public static string BusVerifiCredentials {
            get {
                return ResourceManager.GetString("BusVerifiCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a wallet.
        /// </summary>
        public static string BusWalledTransfer {
            get {
                return ResourceManager.GetString("BusWalledTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The code provided does not match the code sent by email..
        /// </summary>
        public static string CodeNotMatch {
            get {
                return ResourceManager.GetString("CodeNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The time of the code provided has expired..
        /// </summary>
        public static string CodeTimeExpired {
            get {
                return ResourceManager.GetString("CodeTimeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account does not exist.
        /// </summary>
        public static string DatAccountNoExits {
            get {
                return ResourceManager.GetString("DatAccountNoExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account not recovered.
        /// </summary>
        public static string DatAccountNoRecovered {
            get {
                return ResourceManager.GetString("DatAccountNoRecovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account requested for recovery does not exist..
        /// </summary>
        public static string DatAccountSolicitadeNoExits {
            get {
                return ResourceManager.GetString("DatAccountSolicitadeNoExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The parameter was added successfully..
        /// </summary>
        public static string DatAddSuccesParameter {
            get {
                return ResourceManager.GetString("DatAddSuccesParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information was added successfully..
        /// </summary>
        public static string DatAddSuccessInfo {
            get {
                return ResourceManager.GetString("DatAddSuccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not completed correctly..
        /// </summary>
        public static string DatCompleteFailed {
            get {
                return ResourceManager.GetString("DatCompleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completed correctly..
        /// </summary>
        public static string DatCompleteSucces {
            get {
                return ResourceManager.GetString("DatCompleteSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registered not deleted.
        /// </summary>
        public static string DatDeleteFailed {
            get {
                return ResourceManager.GetString("DatDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successfully removed.
        /// </summary>
        public static string DatDeleteSucess {
            get {
                return ResourceManager.GetString("DatDeleteSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All RefreshTokens have been disabled..
        /// </summary>
        public static string DatDesactivateTokens {
            get {
                return ResourceManager.GetString("DatDesactivateTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexpected error occurred.
        /// </summary>
        public static string DatErrorGeneric {
            get {
                return ResourceManager.GetString("DatErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown error, failed to save recovery token.
        /// </summary>
        public static string DatErrorTokenRecover {
            get {
                return ResourceManager.GetString("DatErrorTokenRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The locations were obtained correctly..
        /// </summary>
        public static string DatGetLocatiosSucces {
            get {
                return ResourceManager.GetString("DatGetLocatiosSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The virtual card was obtained successfully..
        /// </summary>
        public static string DatGetMonederoSuccess {
            get {
                return ResourceManager.GetString("DatGetMonederoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The parameters were obtained correctly..
        /// </summary>
        public static string DatGetSuccesParameter {
            get {
                return ResourceManager.GetString("DatGetSuccesParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information was obtained successfully..
        /// </summary>
        public static string DatGetSuccessInfo {
            get {
                return ResourceManager.GetString("DatGetSuccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favorite location does not exist.
        /// </summary>
        public static string DatLocationFavoriteNoExist {
            get {
                return ResourceManager.GetString("DatLocationFavoriteNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unregistered location.
        /// </summary>
        public static string DatLocationNoRegistered {
            get {
                return ResourceManager.GetString("DatLocationNoRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Virtual card not found..
        /// </summary>
        public static string DatMonederoNotFound {
            get {
                return ResourceManager.GetString("DatMonederoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information was not added..
        /// </summary>
        public static string DatNoAddInfo {
            get {
                return ResourceManager.GetString("DatNoAddInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The parameter was not added..
        /// </summary>
        public static string DatNoAddParameter {
            get {
                return ResourceManager.GetString("DatNoAddParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unregistered suggestion.
        /// </summary>
        public static string DatNoAddSuggestion {
            get {
                return ResourceManager.GetString("DatNoAddSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No changes to save.
        /// </summary>
        public static string DatNoChanges {
            get {
                return ResourceManager.GetString("DatNoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are no tickets available..
        /// </summary>
        public static string DatNoExistBoleto {
            get {
                return ResourceManager.GetString("DatNoExistBoleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are no favorite locations..
        /// </summary>
        public static string DatNoExistFavoriteUbications {
            get {
                return ResourceManager.GetString("DatNoExistFavoriteUbications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are no parameters..
        /// </summary>
        public static string DatNoExistParameters {
            get {
                return ResourceManager.GetString("DatNoExistParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is no record..
        /// </summary>
        public static string DatNoExistRegister {
            get {
                return ResourceManager.GetString("DatNoExistRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The record to delete was not found..
        /// </summary>
        public static string DatNoExistRegisterDelete {
            get {
                return ResourceManager.GetString("DatNoExistRegisterDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The parameter to update does not exist..
        /// </summary>
        public static string DatNoExistUpdateParameter {
            get {
                return ResourceManager.GetString("DatNoExistUpdateParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user with the verified account was not found..
        /// </summary>
        public static string DatNoExistUserVerificated {
            get {
                return ResourceManager.GetString("DatNoExistUserVerificated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The record was not found..
        /// </summary>
        public static string DatNoGetRegister {
            get {
                return ResourceManager.GetString("DatNoGetRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not add to refresh token history..
        /// </summary>
        public static string DatNoHistoryRefresToken {
            get {
                return ResourceManager.GetString("DatNoHistoryRefresToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It has no RefreshToken associated with it..
        /// </summary>
        public static string DatNoRefreshTokens {
            get {
                return ResourceManager.GetString("DatNoRefreshTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No record found for the requested token..
        /// </summary>
        public static string DatNoRegisteredToken {
            get {
                return ResourceManager.GetString("DatNoRegisteredToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unsaved data.
        /// </summary>
        public static string DatNoSave {
            get {
                return ResourceManager.GetString("DatNoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The verification code could not be updated..
        /// </summary>
        public static string DatNoUpdateCodeVerification {
            get {
                return ResourceManager.GetString("DatNoUpdateCodeVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The record to update was not found..
        /// </summary>
        public static string DatNoUpdateExist {
            get {
                return ResourceManager.GetString("DatNoUpdateExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The parameter was not updated..
        /// </summary>
        public static string DatNoUpdateParameter {
            get {
                return ResourceManager.GetString("DatNoUpdateParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password could not be updated, the process has already been completed or the time given for changing the password has expired..
        /// </summary>
        public static string DatNoUpdatePassword {
            get {
                return ResourceManager.GetString("DatNoUpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not update account verification status..
        /// </summary>
        public static string DatNoUseStatusAccount {
            get {
                return ResourceManager.GetString("DatNoUseStatusAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred.
        /// </summary>
        public static string DatOcurredError {
            get {
                return ResourceManager.GetString("DatOcurredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The parameter.
        /// </summary>
        public static string DatParameterCompuest1 {
            get {
                return ResourceManager.GetString("DatParameterCompuest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a does not exist..
        /// </summary>
        public static string DatParameterCompuest2 {
            get {
                return ResourceManager.GetString("DatParameterCompuest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The new password must be different from the previous one..
        /// </summary>
        public static string DatPasswordDiferent {
            get {
                return ResourceManager.GetString("DatPasswordDiferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The random password must be different from the previous one..
        /// </summary>
        public static string DatPasswordRandom {
            get {
                return ResourceManager.GetString("DatPasswordRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The wallet did not change.
        /// </summary>
        public static string DatPurseNoChanges {
            get {
                return ResourceManager.GetString("DatPurseNoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is already linked..
        /// </summary>
        public static string DatRegisteredCard {
            get {
                return ResourceManager.GetString("DatRegisteredCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The record does not exist.
        /// </summary>
        public static string DatRegisterNoExist {
            get {
                return ResourceManager.GetString("DatRegisterNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The parameter was updated successfully..
        /// </summary>
        public static string DatSuccesUpdateParameter {
            get {
                return ResourceManager.GetString("DatSuccesUpdateParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a After the time for account recovery has expired, try again..
        /// </summary>
        public static string DatTimeOutAccount {
            get {
                return ResourceManager.GetString("DatTimeOutAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recovery timeout had already ended, please try again.
        /// </summary>
        public static string DatTimeTerminateAccount {
            get {
                return ResourceManager.GetString("DatTimeTerminateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The token is now inactive..
        /// </summary>
        public static string DatTokenInactive {
            get {
                return ResourceManager.GetString("DatTokenInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Token not stored.
        /// </summary>
        public static string DatTokenNoSave {
            get {
                return ResourceManager.GetString("DatTokenNoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The tokens sent are not valid..
        /// </summary>
        public static string DatTokenNoValids {
            get {
                return ResourceManager.GetString("DatTokenNoValids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The tokens were obtained successfully..
        /// </summary>
        public static string DatTokensSucess {
            get {
                return ResourceManager.GetString("DatTokensSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Token used.
        /// </summary>
        public static string DatTokenUsed {
            get {
                return ResourceManager.GetString("DatTokenUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registered not updated.
        /// </summary>
        public static string DatUpdateFailed {
            get {
                return ResourceManager.GetString("DatUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successfully updated.
        /// </summary>
        public static string DatUpdateSucces {
            get {
                return ResourceManager.GetString("DatUpdateSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User not found.
        /// </summary>
        public static string DatUserNoExist {
            get {
                return ResourceManager.GetString("DatUserNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The requested user is not available..
        /// </summary>
        public static string DatUserSolicitadeNoAviable {
            get {
                return ResourceManager.GetString("DatUserSolicitadeNoAviable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registered not verified.
        /// </summary>
        public static string DatVerificateFailed {
            get {
                return ResourceManager.GetString("DatVerificateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successfully verified.
        /// </summary>
        public static string DatVerificateSucces {
            get {
                return ResourceManager.GetString("DatVerificateSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify your email.
        /// </summary>
        public static string DatVerifyEmail {
            get {
                return ResourceManager.GetString("DatVerifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while generating the verification code..
        /// </summary>
        public static string ErrorGeneratedCode {
            get {
                return ResourceManager.GetString("ErrorGeneratedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It will only be available for 48 hours..
        /// </summary>
        public static string Html48Hours {
            get {
                return ResourceManager.GetString("Html48Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request, account cancellation..
        /// </summary>
        public static string HtmlAccountCancelation {
            get {
                return ResourceManager.GetString("HtmlAccountCancelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amount.
        /// </summary>
        public static string HtmlAmount {
            get {
                return ResourceManager.GetString("HtmlAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transport application.
        /// </summary>
        public static string HtmlAplicateTransport {
            get {
                return ResourceManager.GetString("HtmlAplicateTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a to the transportation app.
        /// </summary>
        public static string HtmlAppTransporte {
            get {
                return ResourceManager.GetString("HtmlAppTransporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balance Purchase.
        /// </summary>
        public static string HtmlBalancePurchase {
            get {
                return ResourceManager.GetString("HtmlBalancePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The verification code will be valid for 30 minutes..
        /// </summary>
        public static string HtmlCodeValidity {
            get {
                return ResourceManager.GetString("HtmlCodeValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your verification code..
        /// </summary>
        public static string HtmlCodeVerification {
            get {
                return ResourceManager.GetString("HtmlCodeVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comment.
        /// </summary>
        public static string HtmlComent {
            get {
                return ResourceManager.GetString("HtmlComent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concept.
        /// </summary>
        public static string HtmlConcept {
            get {
                return ResourceManager.GetString("HtmlConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation email.
        /// </summary>
        public static string HtmlConfirmationEmail {
            get {
                return ResourceManager.GetString("HtmlConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact.
        /// </summary>
        public static string HtmlContact {
            get {
                return ResourceManager.GetString("HtmlContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        public static string HtmlDate {
            get {
                return ResourceManager.GetString("HtmlDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date and time.
        /// </summary>
        public static string HtmlDateAndTime {
            get {
                return ResourceManager.GetString("HtmlDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a your account deletion request.
        /// </summary>
        public static string HtmlDelAccount {
            get {
                return ResourceManager.GetString("HtmlDelAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deleted account.
        /// </summary>
        public static string HtmlDeletedAccount {
            get {
                return ResourceManager.GetString("HtmlDeletedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a and we have proceeded to delete your data and information related to your profile, access and registration. No further action is required..
        /// </summary>
        public static string HtmlDelInfo {
            get {
                return ResourceManager.GetString("HtmlDelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a to.
        /// </summary>
        public static string HtmlDestiny {
            get {
                return ResourceManager.GetString("HtmlDestiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please do not share it with anyone..
        /// </summary>
        public static string HtmlDontShare {
            get {
                return ResourceManager.GetString("HtmlDontShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can also download the application at:.
        /// </summary>
        public static string HtmlDownloadApp {
            get {
                return ResourceManager.GetString("HtmlDownloadApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter this verification code where you were asked:.
        /// </summary>
        public static string HtmlEnterCode {
            get {
                return ResourceManager.GetString("HtmlEnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yucatan State Government.
        /// </summary>
        public static string HtmlGob {
            get {
                return ResourceManager.GetString("HtmlGob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Greetings.
        /// </summary>
        public static string HtmlGreetings {
            get {
                return ResourceManager.GetString("HtmlGreetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hello.
        /// </summary>
        public static string HtmlHello {
            get {
                return ResourceManager.GetString("HtmlHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Important.
        /// </summary>
        public static string HtmlImportant {
            get {
                return ResourceManager.GetString("HtmlImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you did not perform the operation indicated in this confirmation, please contact a customer service representative by calling {telefono} or send an email to {email} and provide the reference number..
        /// </summary>
        public static string HtmlImportantLabel {
            get {
                return ResourceManager.GetString("HtmlImportantLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        public static string HtmlInfo {
            get {
                return ResourceManager.GetString("HtmlInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This email is informational, please do not respond, you are not enabled to receive messages..
        /// </summary>
        public static string HtmlInfoEmail {
            get {
                return ResourceManager.GetString("HtmlInfoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Infrastructure type.
        /// </summary>
        public static string HtmlInfraType {
            get {
                return ResourceManager.GetString("HtmlInfraType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is.
        /// </summary>
        public static string HtmlIs {
            get {
                return ResourceManager.GetString("HtmlIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Password.
        /// </summary>
        public static string HtmlNewPass {
            get {
                return ResourceManager.GetString("HtmlNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation details.
        /// </summary>
        public static string HtmlOperationDetails {
            get {
                return ResourceManager.GetString("HtmlOperationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation folio.
        /// </summary>
        public static string HtmlOperationFolio {
            get {
                return ResourceManager.GetString("HtmlOperationFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a from.
        /// </summary>
        public static string HtmlOrigin {
            get {
                return ResourceManager.GetString("HtmlOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please do so, otherwise you will not be able to log in to the app. You can also cancel it by copying and pasting the following link into your browser..
        /// </summary>
        public static string HtmlPassWarning {
            get {
                return ResourceManager.GetString("HtmlPassWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recover your password.
        /// </summary>
        public static string HtmlRecoverYourPassword {
            get {
                return ResourceManager.GetString("HtmlRecoverYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your registration has been completed successfully!.
        /// </summary>
        public static string HtmlRegisterSuccess {
            get {
                return ResourceManager.GetString("HtmlRegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We remind you of your folio number:.
        /// </summary>
        public static string HtmlRemember {
            get {
                return ResourceManager.GetString("HtmlRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We remind you to log in and change your password. The one we share with you is temporary and.
        /// </summary>
        public static string HtmlRememberPass {
            get {
                return ResourceManager.GetString("HtmlRememberPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have requested to recover your account password. To assign a new password click on the following button..
        /// </summary>
        public static string HtmlRePassInfo {
            get {
                return ResourceManager.GetString("HtmlRePassInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report.
        /// </summary>
        public static string HtmlReport {
            get {
                return ResourceManager.GetString("HtmlReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reported by.
        /// </summary>
        public static string HtmlReportedBy {
            get {
                return ResourceManager.GetString("HtmlReportedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incident report.
        /// </summary>
        public static string HtmlReportIncide {
            get {
                return ResourceManager.GetString("HtmlReportIncide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request, verification Code.
        /// </summary>
        public static string HtmlRequestVerificationCode {
            get {
                return ResourceManager.GetString("HtmlRequestVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Route.
        /// </summary>
        public static string HtmlRoute {
            get {
                return ResourceManager.GetString("HtmlRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We send you your verification code.
        /// </summary>
        public static string HtmlSendCode {
            get {
                return ResourceManager.GetString("HtmlSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We send you the password so you can access..
        /// </summary>
        public static string HtmlSendTemporalPass {
            get {
                return ResourceManager.GetString("HtmlSendTemporalPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temporal password.
        /// </summary>
        public static string HtmlTemporalPassword {
            get {
                return ResourceManager.GetString("HtmlTemporalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transfer.
        /// </summary>
        public static string HtmlTransfer {
            get {
                return ResourceManager.GetString("HtmlTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type.
        /// </summary>
        public static string HtmlType {
            get {
                return ResourceManager.GetString("HtmlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unit.
        /// </summary>
        public static string HtmlUnid {
            get {
                return ResourceManager.GetString("HtmlUnid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We have received.
        /// </summary>
        public static string HtmlUsReceived {
            get {
                return ResourceManager.GetString("HtmlUsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        public static string HtmlWelcome {
            get {
                return ResourceManager.GetString("HtmlWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cannot perform the operation.
        /// </summary>
        public static string NotAllowOperation {
            get {
                return ResourceManager.GetString("NotAllowOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation not allowed..
        /// </summary>
        public static string OperationNotAllowed {
            get {
                return ResourceManager.GetString("OperationNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid language.
        /// </summary>
        public static string WebLenguajeNoValid {
            get {
                return ResourceManager.GetString("WebLenguajeNoValid", resourceCulture);
            }
        }
    }
}
