INSERT INTO "APPMONEDEROCOMMAND"."PARAMETROS"
    (SNOMBRE,SVALOR,DTFECHACREACION,DTFECHAMODIFICACION,
    DTFECHABAJA,BACTIVO,BBAJA,UIDUSUARIOCREACION,
    UIDUSUARIOBAJA,UIDPARAMETRO,UIDUSUARIOMODIFICACION,BENCRIPTADO,
    SDESCRIPCION)
    SELECT SNOMBRE,SVALOR,DTFECHACREACION,DTFECHAMODIFICACION,
    DTFECHABAJA,BACTIVO,BBAJA,UIDUSUARIOCREACION,
    UIDUSUARIOBAJA,UIDPARAMETRO,UIDUSUARIOMODIFICACION,BENCRIPTADO,
    SDESCRIPCION FROM "APP"."PARAMETROS"
    
    
INSERT INTO "APPMONEDEROCOMMAND"."TIPOSTARIFA"
    (UIDTIPOTARIFA,STIPOTARIFA,SCLAVETIPOTARIFA,ITIPOTARJETA)
    SELECT UIDTIPOTARIFA,STIPOTARIFA,SCLAVETIPOTARIFA,ITIPOTARJETA
    SDESCRIPCION FROM "APP"."TIPOSTARIFA"
    
INSERT INTO "APPMONEDEROCOMMAND"."TIPOOPERACIONES"
    (UIDTIPOOPERACION,SNOMBRE,SCLAVE,IMODULO,BACTIVO,BBAJA)
    SELECT UIDTIPOOPERACION,SNOMBRE,SCLAVE,IMODULO,BACTIVO,BBAJA
    FROM "APP"."TIPOOPERACIONES"
    
 INSERT INTO "APPMONEDEROCOMMAND"."MOTIVOS"
    (UIDMOTIVO,SMOTIVO,BACTIVO,BBAJA,SDESCRIPCION,ITIPO,BPERMITIROPERACIONES,BPERMITIRREACTIVAR,BPERMITIREDITAR)
    SELECT UIDMOTIVO,SMOTIVO,BACTIVO,BBAJA,SDESCRIPCION,ITIPO,BPERMITIROPERACIONES,BPERMITIRREACTIVAR,BPERMITIREDITAR
    FROM "APP"."MOTIVOS"
    
  INSERT INTO "APPMONEDEROCOMMAND"."USUARIO"
    (UIDUSUARIOTT,SNOMBRE,SAPELLIDOPATERNO,SAPELLIDOMATERNO,STELEFONO,
	SCORREO,SCONTRASENA,SCODIGOVERIFICACION ,BCUENTAVERIFICADA,DTFECHANACIMIENTO,SCURP,
	CGENERO,UIDREDSOCIALGOOGLE,SREDSOCIALGOOGLE,UIDREDSOCIALFACEBOOK,SREDSOCIALFACEBOOK,
	UIDREDSOCIALAPPLE,SREDSOCIALAPPLE,SFOTOGRAFIA,BMIGRADO,DTFECHAVENCIMIENTOCONTRASENA,
	DTFECHACREACION,DTFECHAMODIFICACION,DTFECHABAJA,UIDMONEDEROTT,BACTIVO,
	BBAJA,UIDUSUARIOCREACIONTT,UIDUSUARIOMODIFICACIONTT,UIDUSUARIOBAJATT,UIDUSUARIO,
	UIDMONEDERO,UIDUSUARIOCREACION,UIDUSUARIOMODIFICACION,UIDUSUARIOBAJA,SLADA,
	SIDAPLICACION,IESTATUSCUENTA)
    SELECT UIDUSUARIOTT,SNOMBRE,SAPELLIDOPATERNO,SAPELLIDOMATERNO,STELEFONO,
	SCORREO,SCONTRASENA,SCODIGOVERIFICACION ,BCUENTAVERIFICADA,DTFECHANACIMIENTO,SCURP,
	CGENERO,UIDREDSOCIALGOOGLE,SREDSOCIALGOOGLE,UIDREDSOCIALFACEBOOK,SREDSOCIALFACEBOOK,
	UIDREDSOCIALAPPLE,SREDSOCIALAPPLE,SFOTOGRAFIA,BMIGRADO,DTFECHAVENCIMIENTOCONTRASENA,
	DTFECHACREACION,DTFECHAMODIFICACION,DTFECHABAJA,UIDMONEDEROTT,BACTIVO,
	BBAJA,UIDUSUARIOCREACIONTT,UIDUSUARIOMODIFICACIONTT,UIDUSUARIOBAJATT,UIDUSUARIO,
	UIDMONEDERO,UIDUSUARIOCREACION,UIDUSUARIOMODIFICACION,UIDUSUARIOBAJA,SLADA,
	SIDAPLICACION,IESTATUSCUENTA
    FROM "APP"."USUARIO"
    
     INSERT INTO "APPMONEDEROCOMMAND"."FIREBASETOKEN"
    (UIDFIREBASETOKENTT,UIDUSUARIOTT,SFCMTOKEN,DTFECHACREACION,
    DTFECHAMODIFICACION,DTFECHABAJA,BACTIVO,BBAJA,
    SINFOAPPOS,UIDFIREBASETOKEN,UIDUSUARIO,UIDUSUARIOCREACION,
    UIDUSUARIOMODIFICACION,UIDUSUARIOBAJA,SIDAPLICACION)
    SELECT UIDFIREBASETOKENTT,UIDUSUARIOTT,SFCMTOKEN,DTFECHACREACION,
    DTFECHAMODIFICACION,DTFECHABAJA,BACTIVO,BBAJA,
    SINFOAPPOS,UIDFIREBASETOKEN,UIDUSUARIO,UIDUSUARIOCREACION,
    UIDUSUARIOMODIFICACION,UIDUSUARIOBAJA,SIDAPLICACION
    FROM "APP"."FIREBASETOKEN"

    INSERT INTO "APPMONEDEROCOMMAND"."ESTADODECUENTA"
    (UIDESTADODECUENTA,UIDMONEDERO,UIDTIPOTARIFA,UIDULTIMAOPERACION,
    UIDESTATUS,INUMMONEDERO,DSALDO,STIPOTARIFA,STELEFONO,
    SESTATUS,BACTIVO,BBAJA,DTFECHAULTIMAOPERACION,DTFECHAULTIMOABONO,DTFECHACREACION,
    DTFECHABAJA,SNOMBRE,SAPELLIDOPATERNO,SAPELLIDOMATERNO,
    SCORREO,SFECHAVIGENCIA,DTFECHANACIMIENTO,UIDTIPOMONEDERO,
    STIPOMONEDERO,INUMTARJETA,UIDMOTIVO,SPANHASH)
    SELECT UIDESTADODECUENTA,UIDMONEDERO,UIDTIPOTARIFA,UIDULTIMAOPERACION,
    UIDESTATUS,INUMMONEDERO,DSALDO,STIPOTARIFA,STELEFONO,
    SESTATUS,BACTIVO,BBAJA,DTFECHAULTIMAOPERACION,DTFECHAULTIMOABONO,DTFECHACREACION,
    DTFECHABAJA,SNOMBRE,SAPELLIDOPATERNO,SAPELLIDOMATERNO,
    SCORREO,SFECHAVIGENCIA,DTFECHANACIMIENTO,UIDTIPOMONEDERO,
    STIPOMONEDERO,INUMTARJETA,UIDMOTIVO,SPANHASH
     FROM "APP"."ESTADODECUENTA"
     
      INSERT INTO "APPMONEDEROCOMMAND"."TARJETAS"
    (	
    UIDTARJETA, INUMEROMONEDERO, INUMEROTARJETA, DTFECHAFABRICACION, 
	SVIGENCIA, UIDESTATUSTARJETA, SNOMBREPROVEEDOR, BVENDIDA, 
	BASOCIADA, UIDTIPOTARIFA, DTFECHAMODIFICACION, DTFECHABAJA, 
	BACTIVO, BBAJA, UIDUSUARIOCREACION, UIDUSUARIOMODIFICACION, 
	UIDUSUARIOBAJA, DTFECHACREACION, UIDSOLICITUD, SCCV, 
	BINICIALIZADA, STELEFONO, UIDMONEDERO, SFOLIO, 
	INUMEROPROVEEDOR, UIDMOTIVO, SSKU, UIDUSUARIOTARJETA, 
	SPANHASH, DTFECHAVALIDEZ, UIDDETALLESOLICITUD)
    SELECT 	UIDTARJETA, INUMEROMONEDERO, INUMEROTARJETA, DTFECHAFABRICACION, 
	SVIGENCIA, UIDESTATUSTARJETA, SNOMBREPROVEEDOR, BVENDIDA, 
	BASOCIADA, UIDTIPOTARIFA, DTFECHAMODIFICACION, DTFECHABAJA, 
	BACTIVO, BBAJA, UIDUSUARIOCREACION, UIDUSUARIOMODIFICACION, 
	UIDUSUARIOBAJA, DTFECHACREACION, UIDSOLICITUD, SCCV, 
	BINICIALIZADA, STELEFONO, UIDMONEDERO, SFOLIO, 
	INUMEROPROVEEDOR, UIDMOTIVO, SSKU, UIDUSUARIOTARJETA, 
	SPANHASH, DTFECHAVALIDEZ, UIDDETALLESOLICITUD
    FROM "CREDENCIALIZACION"."TARJETAS"
    
