CREATE TABLE MONEDERO 
(
  UIDMONEDERO RAW(16) NOT NULL 
, DSALDO NUMBER(10, 2) DEFAULT 0 NOT NULL 
, DTFECHACREACION DATE NOT NULL 
, DTFECHAMODIFICACION DATE 
, DTFECHABAJA DATE 
, BACTIVO NUMBER(1, 0) 
, BBAJA NUMBER(1,0) 
, UIDUSUARIOCREACION RAW(16) NOT NULL 
, UIDUSUARIOMODIFICACION RAW(16) 
, UIDUSUARIOBAJA RAW(16) 
);

COMMENT ON COLUMN MONEDERO.UIDMONEDERO IS 'Identificador de monedero';

COMMENT ON COLUMN MONEDERO.DSALDO IS 'Saldo del monedero';

COMMENT ON COLUMN MONEDERO.DTFECHACREACION IS 'Fecha de creaci�n';

COMMENT ON COLUMN MONEDERO.DTFECHAMODIFICACION IS 'Fecha en que se modifico';

COMMENT ON COLUMN MONEDERO.DTFECHABAJA IS 'Fecha de baja';

COMMENT ON COLUMN MONEDERO.BACTIVO IS 'Esta activo';

COMMENT ON COLUMN MONEDERO.BBAJA IS 'Es baja';

COMMENT ON COLUMN MONEDERO.UIDUSUARIOCREACION IS 'Usuario creador';

COMMENT ON COLUMN MONEDERO.UIDUSUARIOMODIFICACION IS 'Usuario que modifico';

COMMENT ON COLUMN MONEDERO.UIDUSUARIOBAJA IS 'Usuario que dio de baja';
