CREATE TABLE MOVIMIENTOS 
(
  UIDMOVIMENTO RAW(16) NOT NULL 
, UIDMONEDERO RAW(16) 
, UIDTIPOMOVIMIENTO RAW(16) 
, STIPOMOVIMIENTO VARCHAR2(50) 
, DSALDOANTERIOR NUMBER(16, 2) NOT NULL 
, DIMPORTE NUMBER(16, 2) NOT NULL 
, DSALDOACTUAL NUMBER(16, 2) NOT NULL 
, DTFECHAOPERACION DATE 
, UIDREFERENCIA RAW(16) 
, DTFECHACREACION DATE NOT NULL 
, DTFECHAMODIFICACION DATE 
, DTFECHABAJA DATE 
, BACTIVO NUMBER(1,0) DEFAULT 1 
, BBAJA NUMBER(1,0) 
, UIDUSUARIOCREACION RAW(16) NOT NULL 
, UIDUSUARIOMODIFICACION RAW(16) 
, UIDUSUARIOBAJA RAW(16) 
, CONSTRAINT MOVIMIENTOS_PK PRIMARY KEY 
  (
    UIDMOVIMENTO 
  )
  ENABLE 
);

COMMENT ON COLUMN MOVIMIENTOS.UIDMOVIMENTO IS 'Identificador del movimiento';

COMMENT ON COLUMN MOVIMIENTOS.UIDMONEDERO IS 'Identificador del movimiento';

COMMENT ON COLUMN MOVIMIENTOS.UIDTIPOMOVIMIENTO IS 'Identificador del tipo movimiento';

COMMENT ON COLUMN MOVIMIENTOS.STIPOMOVIMIENTO IS 'Nombre del movimiento';

COMMENT ON COLUMN MOVIMIENTOS.DSALDOANTERIOR IS 'Saldo anterior al movimiento';

COMMENT ON COLUMN MOVIMIENTOS.DIMPORTE IS 'Importe';

COMMENT ON COLUMN MOVIMIENTOS.DSALDOACTUAL IS 'Saldo actual del movimiento';

COMMENT ON COLUMN MOVIMIENTOS.DTFECHAOPERACION IS 'Fecha en que se realizo la operación';

COMMENT ON COLUMN MOVIMIENTOS.UIDREFERENCIA IS 'Identificador de referencia';

COMMENT ON COLUMN MOVIMIENTOS.DTFECHACREACION IS 'Fecha de creación';

COMMENT ON COLUMN MOVIMIENTOS.DTFECHAMODIFICACION IS 'Fecha en que se modifico';

COMMENT ON COLUMN MOVIMIENTOS.DTFECHABAJA IS 'Fecha de baja';

COMMENT ON COLUMN MOVIMIENTOS.BACTIVO IS 'Esta activo';

COMMENT ON COLUMN MOVIMIENTOS.BBAJA IS 'Es baja';

COMMENT ON COLUMN MOVIMIENTOS.UIDUSUARIOCREACION IS 'Usuario creador';

COMMENT ON COLUMN MOVIMIENTOS.UIDUSUARIOMODIFICACION IS 'Usuario que modifico';

COMMENT ON COLUMN MOVIMIENTOS.UIDUSUARIOBAJA IS 'Usuario que dio de baja';
