CREATE TABLE PERFILTARJETA 
(
  UIDPERFIL RAW(16) NOT NULL 
, SNOMBRE VARCHAR2(50) NOT NULL 
, SDESCRIPCION VARCHAR2(100) 
, DTFECHACREACION DATE NOT NULL 
, DTFECHAMODIFICACION DATE 
, DTFECHABAJA DATE 
, BACTIVO NUMBER(1,0) DEFAULT 1 NOT NULL 
, BBAJA NUMBER(1,0) 
, UIDUSUARIOCREACION RAW(16) NOT NULL 
, UIDUSUARIOMODIFICACION RAW(16) 
, UIDUSUARIOBAJA RAW(16) 
, CONSTRAINT PERFILTARJETA_PK PRIMARY KEY 
  (
    UIDPERFIL 
  )
  ENABLE 
);

COMMENT ON COLUMN PERFILTARJETA.UIDPERFIL IS 'Identificador de perfil';

COMMENT ON COLUMN PERFILTARJETA.SNOMBRE IS 'Nombre de perfil';

COMMENT ON COLUMN PERFILTARJETA.SDESCRIPCION IS 'Descripción del perfil';

COMMENT ON COLUMN PERFILTARJETA.DTFECHACREACION IS 'Fecha de creación';

COMMENT ON COLUMN PERFILTARJETA.DTFECHAMODIFICACION IS 'Fecha en que se modifico';

COMMENT ON COLUMN PERFILTARJETA.DTFECHABAJA IS 'Fecha de baja';

COMMENT ON COLUMN PERFILTARJETA.BACTIVO IS 'Esta activo';

COMMENT ON COLUMN PERFILTARJETA.BBAJA IS 'Es baja';

COMMENT ON COLUMN PERFILTARJETA.UIDUSUARIOCREACION IS 'Usuario creador';

COMMENT ON COLUMN PERFILTARJETA.UIDUSUARIOMODIFICACION IS 'Usuario que modifico';

COMMENT ON COLUMN PERFILTARJETA.UIDUSUARIOBAJA IS 'Usuario que dio de baja';
