CREATE TABLE TARJETA 
(
  UIDTARJETA RAW(16) NOT NULL 
, SNUMEROTARJETA VARCHAR2(19) NOT NULL 
, UIDUSUARIO VARCHAR2(20) NOT NULL 
, SNOMBRETITULAR VARCHAR2(240) NOT NULL 
, SFECHAVENCIMIENTO VARCHAR2(4) NOT NULL 
, SNUMEROSEGURIDAD VARCHAR2(3) NOT NULL 
, STIPOTARJETA VARCHAR2(10) NOT NULL 
, BESTATUSTARJETA NUMBER(1,0) NOT NULL 
, BDEFAULT NUMBER(1,0) NOT NULL 
, DFECHAREGISTRO DATE NOT NULL 
, DTFECHACREACION DATE NOT NULL 
, DTFECHAMODIFICACION DATE 
, DTFECHABAJA DATE 
, BACTIVO NUMBER(1,0) DEFAULT 1 NOT NULL 
, BBAJA NUMBER(1,0) 
, UIDUSUARIOCREACION RAW(16) NOT NULL 
, UIDUSUARIOMODIFICACION RAW(16) 
, UIDUSUARIOBAJA RAW(16) 
, CONSTRAINT TARJETA_PK PRIMARY KEY 
  (
    UIDTARJETA 
  )
  ENABLE 
);

COMMENT ON COLUMN TARJETA.UIDTARJETA IS 'Identificador único de la Tarjeta';

COMMENT ON COLUMN TARJETA.SNUMEROTARJETA IS 'Número de Tarjeta';

COMMENT ON COLUMN TARJETA.UIDUSUARIO IS 'Usuario relacionado con la Tarjeta';

COMMENT ON COLUMN TARJETA.SNOMBRETITULAR IS 'Nombre del titular de la Tarjeta';

COMMENT ON COLUMN TARJETA.SFECHAVENCIMIENTO IS 'Fecha de vencimiento de la tarjeta';

COMMENT ON COLUMN TARJETA.SNUMEROSEGURIDAD IS 'Numero de Seguridad de Tarjeta';

COMMENT ON COLUMN TARJETA.STIPOTARJETA IS 'Tipo de Tarjeta ';

COMMENT ON COLUMN TARJETA.BESTATUSTARJETA IS 'Estatus de la Tarjeta';

COMMENT ON COLUMN TARJETA.BDEFAULT IS 'Tarjeta predeterminada/principal';

COMMENT ON COLUMN TARJETA.DFECHAREGISTRO IS 'Fecha de registro de Tarjeta';

COMMENT ON COLUMN TARJETA.DTFECHAMODIFICACION IS 'Fecha en que se modifico';

COMMENT ON COLUMN TARJETA.DTFECHABAJA IS 'Fecha de baja';

COMMENT ON COLUMN TARJETA.BACTIVO IS 'Esta activo';

COMMENT ON COLUMN TARJETA.BBAJA IS 'Es baja';

COMMENT ON COLUMN TARJETA.UIDUSUARIOCREACION IS 'Usuario creador';

COMMENT ON COLUMN TARJETA.UIDUSUARIOMODIFICACION IS 'Usuario que modifico';

COMMENT ON COLUMN TARJETA.UIDUSUARIOBAJA IS 'Usuario que dio de baja';
