CREATE TABLE TARJETAUSUARIO 
(
  UIDTARJETA RAW(16) NOT NULL 
, UIDMONEDERO RAW(16) 
, UIDUSUARIO RAW(16) 
, SNUMEROTARJETA NUMBER(16) 
, SNOMBRETITULAR VARCHAR2(20) 
, DSALDO NUMBER(16,2) DEFAULT 0 
, IIDESTADOTARJETA INT 
, SNOMONEDERO VARCHAR2(16) 
, SNUMSERIE VARCHAR2(8) 
, UIDPERFIL RAW(16) 
, DTFECHAVIGENCIAUNICA DATE 
, DTFECHAVIGENCIAUNICAFIN DATE 
, DTFECHACREACION DATE NOT NULL 
, DTFECHAMODIFICACION DATE 
, DTFECHABAJA DATE 
, BACTIVO NUMBER(1,0) DEFAULT 1 
, BBAJA NUMBER(1,0) 
, UIDUSUARIOCREACION RAW(16) NOT NULL 
, UIDUSUARIOMODIFICACION RAW(16) 
, UIDUSUARIOBAJA RAW(16) 
);

COMMENT ON COLUMN TARJETAUSUARIO.UIDTARJETA IS 'Identificador de Tarjeta Usuario';

COMMENT ON COLUMN TARJETAUSUARIO.UIDMONEDERO IS 'Este campo es referencia al identificador de Monedero';

COMMENT ON COLUMN TARJETAUSUARIO.UIDUSUARIO IS 'Este campo es referencia al identificador de Usuario';

COMMENT ON COLUMN TARJETAUSUARIO.SNUMEROTARJETA IS 'Número de tarjeta';

COMMENT ON COLUMN TARJETAUSUARIO.SNOMBRETITULAR IS 'Nombre del titular de la tarjeta';

COMMENT ON COLUMN TARJETAUSUARIO.DSALDO IS 'Saldo de la tarjeta';

COMMENT ON COLUMN TARJETAUSUARIO.IIDESTADOTARJETA IS 'Estado de la tarjeta';

COMMENT ON COLUMN TARJETAUSUARIO.SNOMONEDERO IS 'Número de Monedero';

COMMENT ON COLUMN TARJETAUSUARIO.SNUMSERIE IS 'Número de serie de la tarjeta';

COMMENT ON COLUMN TARJETAUSUARIO.UIDPERFIL IS 'Este campo es refencia al identificador de Perfil';

COMMENT ON COLUMN TARJETAUSUARIO.DTFECHAVIGENCIAUNICA IS 'Fecha inicio de vigencia';

COMMENT ON COLUMN TARJETAUSUARIO.DTFECHAVIGENCIAUNICAFIN IS 'Fecha fin de vigencia';

COMMENT ON COLUMN TARJETAUSUARIO.DTFECHACREACION IS 'Fecha de creación';

COMMENT ON COLUMN TARJETAUSUARIO.DTFECHAMODIFICACION IS 'Fecha en que se modifico';

COMMENT ON COLUMN TARJETAUSUARIO.DTFECHABAJA IS 'Fecha de baja';

COMMENT ON COLUMN TARJETAUSUARIO.BACTIVO IS 'Esta activo';

COMMENT ON COLUMN TARJETAUSUARIO.BBAJA IS 'Es baja';

COMMENT ON COLUMN TARJETAUSUARIO.UIDUSUARIOCREACION IS 'Usuario creador';

COMMENT ON COLUMN TARJETAUSUARIO.UIDUSUARIOMODIFICACION IS 'Usuario que modifico';

COMMENT ON COLUMN TARJETAUSUARIO.UIDUSUARIOBAJA IS 'Usuario que dio de baja';
