CREATE TABLE TIPOMOVIMIENTO 
(
  UIDTIPOMOVIMIENTO RAW(16) NOT NULL 
, SNOMBRE VARCHAR2(50) NOT NULL 
, DTFECHACREACION DATE NOT NULL 
, DTFECHAMODIFICACION DATE 
, DTFECHABAJA DATE 
, BACTIVO NUMBER(1,0) 
, BBAJA NUMBER(1,0) NOT NULL 
, UIDUSUARIOCREACION RAW(16) NOT NULL 
, UIDUSUARIOMODIFICACION RAW(16) 
, UIDUSUARIOBAJA RAW(16) 
, CONSTRAINT TIPOMOVIMIENTO_PK PRIMARY KEY 
  (
    UIDTIPOMOVIMIENTO 
  )
  ENABLE 
);

COMMENT ON COLUMN TIPOMOVIMIENTO.UIDTIPOMOVIMIENTO IS 'Identificador del tipo de movimiento';

COMMENT ON COLUMN TIPOMOVIMIENTO.SNOMBRE IS 'Nombre del tipo movimiento';

COMMENT ON COLUMN TIPOMOVIMIENTO.DTFECHACREACION IS 'Fecha de creación';

COMMENT ON COLUMN TIPOMOVIMIENTO.DTFECHAMODIFICACION IS 'Fecha en que se modifico';

COMMENT ON COLUMN TIPOMOVIMIENTO.DTFECHABAJA IS 'Fecha de baja';

COMMENT ON COLUMN TIPOMOVIMIENTO.BACTIVO IS 'Esta activo';

COMMENT ON COLUMN TIPOMOVIMIENTO.BBAJA IS 'Es baja';

COMMENT ON COLUMN TIPOMOVIMIENTO.UIDUSUARIOCREACION IS 'Usuario creador';

COMMENT ON COLUMN TIPOMOVIMIENTO.UIDUSUARIOMODIFICACION IS 'Usuario que modifico';

COMMENT ON COLUMN TIPOMOVIMIENTO.UIDUSUARIOBAJA IS 'Usuario que dio de baja';
