CREATE TABLE TRANSFERENCIA 
(
  UIDTRANSFERENCIA RAW(16) NOT NULL 
, UIDMONEDEROORIGEN RAW(16) NOT NULL 
, UIDMONEDERODESTINO RAW(16) NOT NULL 
, DIMPORTE NUMBER(10, 2) NOT NULL 
, FLATITUD FLOAT 
, FLONGITUD FLOAT 
, DTFECHACREACION DATE NOT NULL 
, DTFECHAMODIFICACION DATE 
, DTFECHABAJA DATE 
, BACTIVO NUMBER(1,0) 
, BBAJA NUMBER(1,0) 
, UIDUSUARIOCREACION RAW(16) NOT NULL 
, UIDUSUARIOMODIFICACION RAW(16) 
, UIDUSUARIOBAJA RAW(16) 
, CONSTRAINT TRANSFERENCIA_PK PRIMARY KEY 
  (
    UIDTRANSFERENCIA 
  )
  ENABLE 
);

COMMENT ON COLUMN TRANSFERENCIA.UIDTRANSFERENCIA IS 'Identificador de tranferencia';

COMMENT ON COLUMN TRANSFERENCIA.UIDMONEDEROORIGEN IS 'Monedero origen de importe';

COMMENT ON COLUMN TRANSFERENCIA.FLATITUD IS 'latitud';

COMMENT ON COLUMN TRANSFERENCIA.DTFECHACREACION IS 'Fecha de creación';

COMMENT ON COLUMN TRANSFERENCIA.DTFECHAMODIFICACION IS 'Fecha en que se modifico';

COMMENT ON COLUMN TRANSFERENCIA.DTFECHABAJA IS 'Fecha de baja';

COMMENT ON COLUMN TRANSFERENCIA.BACTIVO IS 'Esta activo';

COMMENT ON COLUMN TRANSFERENCIA.BBAJA IS 'Es baja';

COMMENT ON COLUMN TRANSFERENCIA.UIDUSUARIOCREACION IS 'Usuario creador';

COMMENT ON COLUMN TRANSFERENCIA.UIDUSUARIOMODIFICACION IS 'Usuario que modifico';

COMMENT ON COLUMN TRANSFERENCIA.UIDUSUARIOBAJA IS 'Usuario que dio de baja';
